### ISSUE TITLE
bug(API) : Modifier les documentation de l'API

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1009]
Ci-dessous l’affichage sur carte des résultats pour une requête ne demandant que le territoire guyanais :
https://api.camino.beta.gouv.fr/titres?territoires=guyane

Je confirme que ça télécharge tous les titres et pas seulement ceux de Guyane

**Comment by vmaubert** [comment]
Je pense qu’ils fonctionnent toujours, c’est juste que le filtre « territoires » a été supprimé. 
Il utilisait une recherche textuelle simple qui pouvait retourner de mauvais résultats.

Maintenant pour filtrer sur la Guyane, le paramètre est le suivant : `regions=03`

**Comment by pohayscamino** [comment]
ok mais vu que ça a changé et que ce n'est pas évident, il faudrait quand même qu'on indique ces spécificités dans notre page d'API : https://docs.camino.beta.gouv.fr/01-utilisation/04-flux/

Que penseriez-vous d'un tableau de ce type?



[Liste filtres API.xlsx](https://github.com/MTES-MCT/camino/files/14329855/Liste.filtres.API.xlsx)

**Comment by MichaelBitard** [comment]
J'aurais plutôt l'approche inverse : mettre dans la documentation qu'il n'y a pas de garantie de stabilité de l'API, et supprimer la partie documentation des champs en explicant qu'il faut regarder ce que fait l'interface (On peut même faire une vidéo pour montrer les requêtes qui partent et comment les copier/coller)

En gros, on est que 2, il vaut mieux ne pas figer la documentation et s'interdire de la faire évoluer.
Si les gens veulent construire des trucs avec notre cadastre minier, il vaut mieux les orienter vers data.gouv.fr

**Comment by pohayscamino** [comment]
Documenter automatiquement les filtres de l'API pour récupérer les titres
