### ISSUE TITLE
bug(activité) : Impossible de trouver le rapport absent

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1018]
Je suis sur la liste des activités de monsieur Portel

![Image](https://github.com/MTES-MCT/camino/assets/144020267/a2878a5e-46ee-4c46-98db-0eec421fd26b)

J'ai parcourru les 8 pages et il n'y a aucun rapport absent.

Par contre quand j'appuie sur la colonne statut pour la trier j'ai un rapport absent qui apparait

![Image](https://github.com/MTES-MCT/camino/assets/144020267/afb80a62-80be-4929-a014-22594e7c71b1)

**Comment by vmaubert** [comment]
Surement corrigé grâce à mon nettoyage d’hier

**Comment by pohayscamino** [comment]
Je ne trouve toujours pas le rapport absent pour Grand Marquis (4eme trimestre 2023)

https://preprod.camino.beta.gouv.fr/activites?page=2
