### ISSUE TITLE
feat(cartes): revoir les règles de gestion

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1031]
## Checklist

* [ ] On peut créer un nouveau titre
* [ ] On peut créer une nouvelle étape
* [ ] On peut ajouter un périmètre à une étape
  * [ ] Dans le référentiel 4326
    * [ ] On peut télécharger le geojson dans le référentiel 4326
  * [ ] Dans un autre référentiel
    * [ ] On peut télécharger le geojson dans le référentiel d'origine **et** dans le 4326 (un second bouton apparait)
* [ ] On peut éditer le périmètre d'une étape
* [ ] On peut télécharger les points dans le référentiel d'origine en CSV (vue tableau)

## Besoin

SRID d'import à enregistrer et montrer par défaut dans le tableau
Coordonnées non transformées à montrer par défaut dans le tableau
Si SRID d'import local ajouter seulement le 4326 en plus
Si SRID d'import en 4326 ajouter seulement le SRID local en plus
Besoin de vérifier que les points sont au même endroits que ceux de la géométrie

**Comment by pohayscamino** [comment]
[test_srid.zip](https://github.com/MTES-MCT/camino/files/14375908/test_srid.zip)

**Comment by MichaelBitard** [comment]
Taches à faire :
- Récupérer les périmètres opposables dans le dump archivé et les mettre dans l'application
- Afficher dans le tableau uniquement les points tels qu'ils ont été insérés dans le geosysteme d'origine
- Plus de conversion des points du tableau (pour le moment, à voir ce qu'on remet plus tard)

**Comment by pohayscamino** [comment]
Quand on telecharge le CSV ce serait mieux que les décimales soient avec "," plutot que "."
pareil sur ce qu'on voit dans le tableau

**Comment by MichaelBitard** [comment]
C'est un standaaaaaaaaaaaaaard

**Comment by pohayscamino** [comment]
Un standard anglo-saxon non?
Les tableaux des demandes et des décrets sont avec des ","

**Comment by pohayscamino** [comment]
La priorité c'est d'importer des CSV avec des ","
