### ISSUE TITLE
feat(carte) : Importer un csv

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1034]
## Checklist

* [ ] Importer un csv

Permettre d'importer un csv et créer automatiquement une carte à partir du csv

**Comment by MichaelBitard** [comment]
Le format du CSV sert pour les périmètres simples (sans lacunes, ni multi polygones)

Format du CSV:
```csv
nom;description;(x/longitude);(y/latitude)
A;Point A;1051195.108314365847036;6867800.046355471946299
B;Point B;1063526.397924559889361;6867885.978687250986695
C;Point C;1061421.05579599016346;6865050.211738565005362
```
Le header est optionel, le séparateur est le ';'

**Comment by pohayscamino** [comment]
Les décimales sont avec des "," pas des "."

**Comment by MichaelBitard** [comment]
> Les décimales sont avec des "," pas des "."

Je ne suis pas d'accord, dans les fichiers geojson ce sont des '.' et pas des ',' c'est le standard.

Franchement à gérer c'est la plaie, on peut pas imposer ça ?

**Comment by pohayscamino** [comment]
Les champs "nom" et "description" peuvent être à null

**Comment by MichaelBitard** [comment]
> Les champs "nom" et "description" peuvent être à null

Je dirais non.
On est sur un import simple en CSV, tout doit être rempli :)

**Comment by pohayscamino** [comment]
Je vois le souci. En fait on a le même problème que pour les autres formats. On peut vouloir déposer un polygone complexe mais un fichier de points moins complexe. 

Donc avec le bouton "importer un périmètre", on importe csv sur le même principe pour les geojson. Seulement un périmètre (donc une liste de points). Donc que les champs "x" et "y". Et on met automatiquement les noms de points et description (comme pour les autres formats).

Avec le bouton "Editer les points" on importe un csv sur le même principe pour les geojson. Les champs "nom" et "description" peuvent être remplis ou pas pour donner des infos sur les points et on peut mettre moins de points que pour le périmètre (pour que moins de points s'affichent).

**Comment by MichaelBitard** [comment]
Non pour moi le bouton "éditer les points" on importe pas de csv.
L'import de csv c'est uniquement pour simplifier la vie des gens qui ne veulent pas utiliser qgis, du coup ils sont rien d'autre à faire que d'importer le périmère en csv avec tous les champs remplis (nom, description, lat/x/lon/y) et c'est tout

**Comment by pohayscamino** [comment]
Remplacer, mettre à la ligne et sauter une ligne "Pour plus d'informations sur la création d'un périmètre et son dépôt vous pouvez regarder ce [tutoriel](https://dai.ly/x8spe70)." par "Le dépôt csv n'est possible que pour des périmètres simples : un seul polygone sans lacunes ayant moins de 20 sommets."

**Comment by MichaelBitard** [comment]
@pohayscamino sans lacunes ou sans lacune dans le texte ?

**Comment by pohayscamino** [comment]
sans lacune
