### ISSUE TITLE
feat(sécurité): Vérifier l'entête des fichiers PDFs

### ISSUE THREAD

**Issue by MichaelBitard** [MTES-MCT/camino#1037]
## Checklist

* [ ] Peut téléverser un fichier pdf (trois endroits différents --> entreprise, activite, document)
* [ ] Peut téléverser un fichier geojson, shape, csv (sur les périmètres)
* [ ] Ne peut pas téléverser un fichier autre que pdf, geojson, shape ou csv (doit remonter une erreur)
* [ ] Ne peut pas téléverser un fichier finissant pas .pdf mais qui n'en est pas un (trois endroits différents --> entreprise, activite, document)

Pour les geojson, shapefile et csv, on vérifie leur contenu avant de les sauvegarder.

Pour les pdfs, il faudrait faire au moins une mini vérification, notamment l'entête binaire du fichier qui doit commencer par `%PDF-`

```node
var fs = require('fs'),
binary = fs.readFileSync('./monpdf.pdf');
process.stdout.write(binary.slice(0, 5));
```

Il faudrait qu'on valide aussi que tous les fichiers pdf qui ont été déposés sur camino passent bien ce nouveau check que l'on va rajouter lors de l'upload de documents

**Comment by pohayscamino** [comment]
J'ai essayé de déposer des fichiers .exe pour le périmètre. Ça refusait les fichiers. Mais après quand j'ai essayé un geojson ça continue de refuser



![Image](https://github.com/MTES-MCT/camino/assets/144020267/37bd2fe1-e64c-47bb-b095-e1c1c234e537)

**Comment by MichaelBitard** [comment]
J'ai l'impression que c'est parce que t'as mis le geosysteme en 4326 et que ton fichier est en 2972 non ?

**Comment by pohayscamino** [comment]
Nope je viens de re-vérifier



![Image](https://github.com/MTES-MCT/camino/assets/144020267/5516d64b-f9ef-4368-b96a-cc0c584790ac)

**Comment by MichaelBitard** [comment]
Envoie le fichier s'il te plait

**Comment by MichaelBitard** [comment]
Ça semble être un problème avec ton fichier, j'arrive bien à uploader des geojson de mon côté.

Par contre il faudrait vraiment qu'on travaille sur les messages d'erreurs sur ces imports de périmètre, pour que l'on sache pourquoi on a une erreur

**Comment by pohayscamino** [comment]
Le fichier


[perimetre-m-ax-1-2-affluent-mana-aval-2022-2972.zip](https://github.com/MTES-MCT/camino/files/14665365/perimetre-m-ax-1-2-affluent-mana-aval-2022-2972.zip)

**Comment by MichaelBitard** [comment]
Je n'ai aucun souci pour téléverser ce polygone...
