### ISSUE TITLE
feat(cartes) : Explications dépôts

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1044]
Dans le "i" du bouton "Importer un périmètre" ajouter le texte suivant : 
- Pour les SRID locaux : "Les fichiers CSV déposés en SRID locaux doivent avoir les 4 champs suivants : "Nom du point", "Description", "X, "Y". 
- Pour 4326 : Les fichiers CSV déposés en SRID 4326 doivent avoir les 4 champs suivants : "Nom du point", "Description", "Longitude", "Latitude".  Seul le champ "Description" peut être à null."

Dans le "i" du bouton "Éditer les points" ajouter le texte suivant : "Les fichiers déposés doivent avoir les 2 champs suivants : "Nom du point", "Description". Seul le champ "Description" peut être à null."

**Comment by MichaelBitard** [comment]
> Dans le "i" du bouton "Éditer les points" ajouter le texte suivant : "Les fichiers déposés doivent avoir les 2 champs suivants : "Nom du point", "Description". Seul le champ "Description" peut être à null."

Je ne suis pas d'accord avec ce texte. Le bouton d'import des *points* n'autorise que le geojson, et le texte est bon :

> Vous pouvez déposer un fichier de points pour modifier ou supprimer les noms et descriptions des points. Votre fichier doit comporter un champ "nom" (nous vous conseillons de ne pas dépasser 3 caractères) et un champ "description".

Tout les champs sont optionnels
