### ISSUE TITLE
feat(cartes) : vérifier que les points déposés sont sur les points du polygone

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1045]
Vérifier que les points déposés sont à l'emplacement des sommets du polygone

**Comment by pohayscamino** [comment]
J'ai telechargé le périmètre du titre suivant : https://preprod.camino.beta.gouv.fr/etapes/g-pr-strasbourg-2013-pr201-mfr01/edition

[perimetre_strasbourg.zip](https://github.com/MTES-MCT/camino/files/14513309/perimetre_strasbourg.zip)



J'ai juste ouvert que la couche de points sur QGIS et l'ai sauvegardée. Je ne peux plus la redéposer....

**Comment by MichaelBitard** [comment]
Oui tout à fait, c'est ça le besoin. Les points ne sont pas sur le périmètre c'est normal qu'on refuse de ré-importer ce périmètre

**Comment by pohayscamino** [comment]
Bon faut qu'on en discute car je ne m'étais pas rendu compte de ces deltas de valeurs et ce que ça entraine. Vous pouvez le désactiver pour le moment pour pas bloquer la prod à cause de ça?
