### ISSUE TITLE
bugg(frise) : Mauvaise date pour la prolongation

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1049]

**Comment by pohayscamino** [comment]
Dans le titre suivant : https://camino.beta.gouv.fr/titres/m-cx-lenoncourt-1968?demarcheSlug=m-cx-lenoncourt-1968-exp02

La date qu'il faudrait mettre à coté de la prolongation c'est la date de début et pas celle de fin.



![Image](https://github.com/MTES-MCT/camino/assets/144020267/13ad437b-330f-490a-8712-506a65b34a0d)

**Comment by MichaelBitard** [comment]
@pohayscamino 

J'ai supprimé la date de fin de l'extension de périmètre en dev et on se retrouve avec quelque chose qui semble plus correct, si tu valides je fais ça en preprod/prod

https://dev.camino.beta.gouv.fr/titres/m-cx-lenoncourt-1968?demarcheSlug=m-cx-lenoncourt-1968-exp01


```sql
update titres_etapes set date_fin=null where slug='m-cx-lenoncourt-1968-exp01-dpu01';
```
Puis éditer/sauvegarder l'étape
