### ISSUE TITLE
feat(cartes) : Nom des champs des fichiers de points

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1050]
J'aurais quand même bien aimé qu'on prenne la même norme pour les nom des champs du geojson de points : "Nom du point", "Description"

Histoire de suivre partout la même norme.

**Comment by MichaelBitard** [comment]
Je laisse @vmaubert me dire si je me trompe, mais ça implique : 

- soit on le change partout, et il faut faire de la migration
- soit on le controle uniquement lors des différentes façons d'importer (csv, geojson) et d'exporter, et ça nous fait dupliquer pas mal de code

**Comment by vmaubert** [comment]
@pohayscamino c’est quoi le rapport entre le nom du ticket et son contenu ?

Concernant le contenu du ticket. Ça va nous générer du taff et pas mal de code pour très peu de valeur ajoutée. Si c’est un problème d’avoir la même norme partout, on peut mettre les entêtes du csv à `nom` et `description`. Pas de taff ni de code superflus.

**Comment by pohayscamino** [comment]
J'avais repris le nom du ticket d'où venait la demande supplémentaire. Mais ça ne fait plus sens alors je viens de changer.

Je ne pense pas que ça serait si lourd. Je pensais que ça demandait juste à modifier deux mots dans le code. Pour moi ce n'est pas mega important alors autant laisser tomber et on verra si des gens font des retours.
