### ISSUE TITLE
feat(simplification) : fusionner les étapes des avis

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1058]
Lié au ticket #779

**Comment by pohayscamino** [comment]
Tu peux m'envoyer des exemples où il y a des contrat ou motif ou lettre pour cette étape stp?

En tout cas le type "avis" et "avis des services civils et militaires" sont utilisés pour la même chose donc oui on les fusionne en un seul type

**Comment by anis** [comment]
Voilà des exemples :
- [https://camino.beta.gouv.fr/titres/m-ar-crique-acajou-2-2015?demarcheSlug=m-ar-crique-acajou-2-2015-oct01](cas avec un document "Motif")
- [https://camino.beta.gouv.fr/titres/m-ax-crique-tete-orapu-aval-2024?demarcheSlug=m-ax-crique-tete-orapu-aval-2024-oct01](cas avec un document "Avis des services civils et militaires")
- [https://camino.beta.gouv.fr/titres/m-ax-bon-espoir-2b-2022?demarcheSlug=m-ax-bon-espoir-2b-2022-oct01](cas avec un document "Avis")
- [https://camino.beta.gouv.fr/titres/m-ar-crique-amont-mousse-2-2020?demarcheSlug=m-ar-crique-amont-mousse-2-2020-ren01](cas avec un document "Lettre")

Pour l'instant, nous partons sur l'idée de fusionner tous ces documents en un seul type "Avis de l'Office National des Forêts", est-ce que c'est ok pour toi ?

**Comment by pohayscamino** [comment]
oui c'est ok

**Comment by MichaelBitard** [comment]
@pohayscamino on a un nouveau souci, pour les étapes  'avis de l'office national des forêts' et 'expertise de l'office national des forêts' il y'a des sections...

pour l'avis, il y'a motifs et signataire (exemple en prod --> https://camino.beta.gouv.fr/titres/m-ar-abattis-kotica-2006?demarcheSlug=m-ar-abattis-kotica-2006-oct01)

pour l'expertise, il y'a motifs, expert, agent et date de début --> https://camino.beta.gouv.fr/titres/m-ar-abattis-kotika-2006?demarcheSlug=m-ar-abattis-kotika-2006-oct01

On en fait quoi ?

**Comment by pohayscamino** [comment]
Ah oui c'est étrange ces infos. Surtout que ce sont des données personnelles.
Je ne vois pas l’intérêt de garder ces infos mais j'ai demandé à l'ONF si on pouvait les supprimer parceque je ne peux pas trop prendre cette décision sans leur accord.

**Comment by pohayscamino** [comment]
Cette étape ne semble pas utile. Donc oui vous pouvez la supprimer.

Pour les étapes déjà existantes, il faut quand même garder les documents qui y étaient déposés (et les appeler  "expertise de l'Office National des Forets" dans la nouvelle étape des avis) et leur mettre la date de l'étape. 

J'ai vu qu'il y avait pas mal de motifs remplis, ce serait bien de tout passer dans la description de l'étape des avis histoire de garder ces infos.

**Comment by vmaubert** [comment]
Je crois qu'on ne s'est pas compris.
C'est une étape privée, réservée à l'ONF. On ne peut pas la rendre publique.
Des fois l'avis de l'ONF est en contradiction avec l'expertise de l'ONF !

**Comment by vmaubert** [comment]
@pohayscamino cool
- ok pour l'avis de l'onf
- heuuuu, tu as créé l'étape de 0 ? Car normalement il y a les 2 boutons :-/

**Comment by pohayscamino** [comment]
lol la boulette. :)

J'ai parlé trop vite donc je retire complètement ce que j'ai dit (y a que les cons qui ne changent jamais d'avis hein). 

J'étais sur une étape déjà existante donc c'est pour ça que je trouvais ça suffisant. Mais pour les nouvelles étapes j'ai montré à des agents EARM2 et ils m'ont bien confirmé que la notion de brouillon était top car il faut vraiment que la DREAL donen l'info que tout a été déposé.

Par contre sur le bouton pouvez-vous mettre "Enregistrer et terminer l'étape" plutôt que "Enregistrer puis déposer l'étape"
