### ISSUE TITLE
feat(referencement) : perte du référencement

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1067]
Quand on met "camino" dans google on est pas trop mal référencé. Si on met  "camino mines", la page beta.gouv arrive en premier et notre site n'est pas sur la première page

**Comment by vmaubert** [comment]
Mais tous les liens parlent de Camino. Donc je ne suis pas certain que ça soit un problème.
Sur Duckduckgo.com le 1er résultat c’est bien notre Camino…
Je propose qu’on ouvre un ticket chez Google ? 🤡 

Tu proposes quoi ? De mon point de vue si tu connais le nom « Camino », c’est que tu sais déjà ce que tu veux. C’est pas ça qui doit être correctement référencé mais plutôt des mots clés comme « Cadastre, minier, France ».
