### ISSUE TITLE
bugg(droits) : Les prefectures n'ont pas accès à l'onglet activité

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1075]
Les préfectures doivent pouvoir voir les rapports d'activité dans l'onglet activités. Elles ne doivent pas pouvoir les modifier en revanche

**Comment by vmaubert** [comment]
A toutes les activités ? Ou seulement aux activités des titres du département de la préfecture ?

**Comment by pohayscamino** [comment]
non tous les rapports que dans son département
