### ISSUE TITLE
feat(erreur) : améliorer les explications des messages d'erreur

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1084]
Améliorer ce qu'indique les messages d'erreur lors des dépôt de périmètres/points/forages

Préciser si l'erreur vient : 
- d'un mauvais SRID
- de champs manquants
- de champs mal remplis
- de points en dehors du périmètre
- d'une mauvaise extension de fichier

**Comment by vmaubert** [comment]
À mettre que sur l'import de périmètre pour commencer.
Mettre le wrapper au dessus de nos appels REST. Pour qu'ils recoivent directement en entrée les params déjà parsés, et qu'on passe tout le temps la sortie dans ZOD pour virer les champs supplémentaires.
À voir si on a besoin de `fpts` (ou d'une solution maison) pour gérer les `either`.

**Comment by pohayscamino** [comment]
Pour les tests : 

- **mauvais SRID**
J'ai déposé ce fichier en indiquant 4326
Le message d'erreur n'est pas très claire je trouve. Mettre plutôt "Problème de SRID"

[perimetre-m-cx-pierre-perthuis-1966-2154.zip](https://github.com/user-attachments/files/16099121/perimetre-m-cx-pierre-perthuis-1966-2154.zip)

![Image](https://github.com/MTES-MCT/camino/assets/144020267/ebf90c96-9b08-43aa-b8ae-b3f63eb28544)


- **champs manquants**
J'ai supprimé le champs nom et ai essayé de déposer le csv. 
[points-m-cx-pierre-perthuis-1966.csv](https://github.com/user-attachments/files/16099160/points-m-cx-pierre-perthuis-1966.csv)

Le message d'erreur n'est pas très claire je trouve. Mettre plutôt  "Champ manquant ou mal nommé"

![Image](https://github.com/MTES-MCT/camino/assets/144020267/c4453136-f005-4c40-a1e1-7a5ec2b77a62)

- **champs mal indiqué**
J'ai modifié le champs nom et ai essayé de déposer le csv. 

[points-m-cx-pierre-perthuis-1966.csv](https://github.com/user-attachments/files/16099197/points-m-cx-pierre-perthuis-1966.csv)

Le message d'erreur n'est pas très claire je trouve. Mettre plutôt  "Champ manquant ou mal nommé"

![Image](https://github.com/MTES-MCT/camino/assets/144020267/26e77d03-f49e-47ce-aad9-8f99879a8070)



- **champs mal remplis**

J'ai mis une lettre dans le champ longitude

[points-m-cx-pierre-perthuis-1966.csv](https://github.com/user-attachments/files/16099219/points-m-cx-pierre-perthuis-1966.csv)

Le message d'erreur n'est pas très claire je trouve. Mettre plutôt  "Les coordonnées doivent être des nombres."

![Image](https://github.com/MTES-MCT/camino/assets/144020267/5b867bc6-a3ae-4188-9005-7fa6027b7e34)


- **points en dehors du périmètre**


J'ai pas pu tester car ça m'a accepté des points en dehors du périmètre



![Image](https://github.com/MTES-MCT/camino/assets/144020267/74784e0f-5371-4b6d-8644-51752ee0237e)



[Perimetre_et_points_hors_perimetre.zip](https://github.com/user-attachments/files/16099261/Perimetre_et_points_hors_perimetre.zip)

**Comment by pohayscamino** [comment]
- mauvais SRID

Le message est bien. Pas besoin d'afficher le message technique

![Image](https://github.com/user-attachments/assets/33aaa595-d661-45d0-a325-e3b31261df98)

- points en dehors du périmètre
En fait on ne permet pas d'enregistrer l'étape donc pas besoin de vérification

**Comment by vmaubert** [comment]
> Pas besoin d'afficher le message technique

C'est pratique pour nous. Souvent les utilisateurs nous envoient un email « ça ne marche pas » avec en PJ un screenshot.

>       En fait on ne permet pas d'enregistrer l'étape donc pas besoin de vérification

Ton fichier n'est pas correct, donc on ne peut pas savoir si les points sont en dehors du périmètre
