### ISSUE TITLE
feat(géothermie): Ajouter les 2 champs supplémentaires

### ISSUE THREAD

**Issue by vmaubert** [MTES-MCT/camino#1087]
see https://github.com/MTES-MCT/camino/issues/924#issuecomment-1970777229

**Comment by pohayscamino** [comment]
Titre servant d’exemple : https://preprod.camino.beta.gouv.fr/titres/g-px-skatepark-2022?demarcheSlug=g-px-skatepark-2022-oct01

Il faudrait qu'on puisse voir les unités aussi des l'étape



![Image](https://github.com/MTES-MCT/camino/assets/144020267/14a0899e-587e-4937-bba3-2b1f20d6b694)



Comme c'est le cas pour le résumé



![Image](https://github.com/MTES-MCT/camino/assets/144020267/be238f03-ee62-443c-9e4d-bd4bb35330bd)

**Comment by MichaelBitard** [comment]
@pohayscamino C'est corrigé en preprod, tu peux re-tester
