### ISSUE TITLE
feat(forages) : Design des forages

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1094]
La taille attendue est plutôt les deux petits points sur le bâtiments : 

![Image](https://github.com/MTES-MCT/camino/assets/144020267/b6fa34af-76c2-4869-a05a-4bb7e801f4da)

Il seraient plus partant pour des points tout en bleu claire pour les captages et tout en rouge pour les rejets.

Captage et rejets pas forcements très proches mais elle m'a montré des exemples ou il y avait plusieurs captages sur le même batiment

Je vous joins un exemple de ce qu'ils ont ASAP.

**Comment by pohayscamino** [comment]
Les visuels de la DREAL ARA

[Visuel2_ZAC Presqu'île_Grenoble_vD.pdf](https://github.com/MTES-MCT/camino/files/14747138/Visuel2_ZAC.Presqu.ile_Grenoble_vD.pdf)
[Visuel1_ZAC Presqu'île_Grenoble_vD.pdf](https://github.com/MTES-MCT/camino/files/14747137/Visuel1_ZAC.Presqu.ile_Grenoble_vD.pdf)

**Comment by vmaubert** [comment]
Voici un aperçu => 

![Image](https://github.com/MTES-MCT/camino/assets/6149841/a56bdd2a-ca33-430d-a36a-aa139831fe44)



- Nous n’avons pas accès à la couleur rouge. Si tu préfères d’autres couleurs, dit moi celles que je dois utiliser parmis les couleurs **illustratives** du DSFR https://www.systeme-de-design.gouv.fr/elements-d-interface/fondamentaux-de-l-identite-de-l-etat/couleurs-palette
- J’ai réduis la taille des forages
- J’ai bougé le label en dessous de chaque forages
- J’ai ajouté le nouveau type « piézomètre », j’ai modifié le forage tout en bas de l’exemple avec ce type

**Comment by pohayscamino** [comment]
La taille des points est trop grosse. Divise par 4.
La taille du label est trop gros. Divise par 2.
Les couleurs sont biens.

**Comment by vmaubert** [comment]
Comme ça ? 
<img width="928" alt="Capture d’écran 2024-03-28 à 09 07 28" src="https://github.com/MTES-MCT/camino/assets/6149841/68563568-d4de-4693-9f28-30ab0670f081">

**Comment by pohayscamino** [comment]
oui très bien
