### ISSUE TITLE
feat(PEX) : Date de validité

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1096]
Pour les PEX Géothermie (et contrairement aux autres titres M), la date de validité du titre court à partir de la publication et pas à partir de l'étape de décision de l'administration

**Comment by vmaubert** [comment]
@pohayscamino J’ai réalisé les modifs dans le code.
Pour moi le comportement attendu est maintenant correct MAIS on a un pb…
L’utilisatrice a mis à chaque fois un octroi et une démarche de travaux.
Vu que l’octroi n’est plus valide, il n’y a plus de phase, et donc le « travaux » éclate l’UI car on ne peut plus le placer sur la timeline.

Exemple => https://dev.camino.beta.gouv.fr/titres/g-px-batiment-confluent-ii-2020?demarcheSlug=g-px-batiment-confluent-ii-2020-oct01

**Comment by pohayscamino** [comment]
ok donc ce que je comprends c'est que pour les titres suivants 


![Image](https://github.com/MTES-MCT/camino/assets/144020267/ae5aade7-1a71-4af9-8e72-d76f68c25bc8)


On a deux choix : 
- soit on crée des étapes de publication pour tous les titres avant que tu mettes la modif en prod
- soit on supprime les travaux pour tous ces titres avant que tu ne mettes en prod

Je vais voir avec la DREAL. Dans le cas du titre (la procédure complète) : https://camino.beta.gouv.fr/titres/g-px-be-flex-2022?demarcheSlug=g-px-be-flex-2022-aom01

Dans le logigramme je ne vois pas l'étape de l'Arrêté d'ouverture des travaux miniers. Je ne comprends pas comment ils ont pu la créer.



![Image](https://github.com/MTES-MCT/camino/assets/144020267/654f2e5e-ce7a-468e-aff8-5c545a13b625)

**Comment by pohayscamino** [comment]
ok en prod. j'ai mis des étapes de publication à tous les titres PEX ayant des travaux. 

Par contre on a un problème sur la date. Je m'explique : 
C'est le même AP qui délivre un titre et qui autorise les travaux. Le titre n'est valide qu'à partir de sa publication mais les travaux sont autorisés à partir de la signature de l'AP. Mais comme on ne peut pas faire de travaux sur une zone pour laquelle on n'a pas de titre valide en réalité il est impossible de faire des travaux entre le moment où l'AP est signé et le moment de la publication.

Néanmoins dans Camino, dans la démarche "Autorisation d'ouverture de travaux" la première étape est "Arrêté d'ouverture des travaux miniers". C'est donc la date de signature de l'AP qui sera mise par les agents (pas la date de publication). Ce qui va faire planter la timeline je pense.

On peut s'en sortir en renommant l'étape "Arrêté d'ouverture des travaux miniers" en "Publication de l'arrêté d'ouverture des travaux miniers". Comme ça les agents mettront la bonne date.

**Comment by vmaubert** [comment]
On vient de réessayer, les travaux ne nous embêtent plus.
Par contre on met des titres à « Échu » car il manque la durée sur quelques titres :
- [ ] aaa98511deebf7d94932bb67
- [ ] 9d8ac811fe1d5749f3ce810c
- [ ] c25270ebfde146a3eee010da
- [ ] f4556f662ac8bfa9b8fa1316
- [ ] d8ee8acc94793dc0e3a09a6e
- [ ] 31fe97f4ef9d6fcd5249ae83

**Comment by pohayscamino** [comment]
vous pouvez y aller. Je vais demander à la DRIEAT de modifier
