### ISSUE TITLE
feat(PEX) : Piezomètres

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1098]
Lors de notre dernier point madame Kanta s'est rendue compte qu'elle avait oublié un type de forage. En plus de captage et rejet, il faut un type "piézomètre". Il doit être représenté de la même façon sur la carte mais avec une couleur spécifique.

Pour les piézomètres, restons sur du orange comme sur la carte.

[Visuel2_ZAC Presqu'île_Grenoble_vD.pdf](https://github.com/MTES-MCT/camino/files/14747167/Visuel2_ZAC.Presqu.ile_Grenoble_vD.pdf)
[Visuel1_ZAC Presqu'île_Grenoble_vD.pdf](https://github.com/MTES-MCT/camino/files/14747168/Visuel1_ZAC.Presqu.ile_Grenoble_vD.pdf)

**Comment by vmaubert** [comment]
see #1094

**Comment by pohayscamino** [comment]
Je n'arrive pas à déposer ce fichier qui est un fichier que j'ai déjà déposé dans lequel j'ai changé un type qui était "rejet" en "piézomètre"

[perimetre-g-px-skatepark-2022-2154_points.csv](https://github.com/MTES-MCT/camino/files/15187623/perimetre-g-px-skatepark-2022-2154_points.csv)

**Comment by pohayscamino** [comment]
J'aurais une autre demande concernant ce ticket. Dans le message d'info est-ce que vous pouvez ajouter : "type" (rejet , captage ou piézomètre), ?



![Image](https://github.com/MTES-MCT/camino/assets/144020267/c808ec8c-9898-493f-9cc7-7cfa713b4d53)
