### ISSUE TITLE
bug(profil) : Inversion des noms et prénoms de certains utilisateurs

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1111]
Les prénoms et noms ont été inversés pour certains utilisateurs. On avait déjà fait une correction pour la DGTM mais je ne me rappelle plus trop d'où venait le souci. Vous pouvez me réexpliquer svp?

![Image](https://github.com/MTES-MCT/camino/assets/144020267/67f5482f-9dac-4bb2-a600-49e2e5c95e97)

**Comment by MichaelBitard** [comment]
On ne sait pas trop, mauvaise saisie utilisateur, mauvaise migration de notre côté :shrug: 

On peut modifier ça directement dans keycloak, mais c'est au cas par cas

**Comment by vmaubert** [comment]
Ils doivent se connecter pour que ça change dans Camino

**Comment by pohayscamino** [comment]
ok j'ai fait le test avec Cécile Caron et ça a bien fonctionné. Par contre je ne vais pas faire tous les autres car il va y avoir des mdp à refaire.
