### ISSUE TITLE
feat(étape): amélioration du formulaire de création/modification d’une étape

### ISSUE THREAD

**Issue by vmaubert** [MTES-MCT/camino#1123]
Suite au point avec Sarah, voici les différentes améliorations à réaliser/tester :

- [ ] Mettre la surface dans les tabs « Carte » et « Table ». Pour que l’héritage remonte et soit plus clair.
- [ ] Quand on active l’héritage il faut désactiver le champ (sauf pour les substances) pour éviter le layout shift 
- [ ] Idem pour les champs des Propriétés spécifiques
- [ ] Pour l’héritage, remplacer le « Non renseigné » par un champ de type Text, désactivé avec dedans « Non renseigné ».
- [ ] Dans les documents d’entreprises, il y a 2 alertes. Il faut afficher que l’une des deux à un temps donné.
- [ ] Pour les autocompletes (titulaires et amodiataires), mettre un label comme pour les DsfrInput

**Comment by pohayscamino** [comment]
Je ne vois pas ce que sont les 2 alertes pour les documents d'entreprises

**Comment by vmaubert** [comment]
Si tu n’as aucun titulaire, ni d’amomidiataire, t’as une alerte du style « Il faut sélectionner un titulaire ».
Et sinon t’as une alerte de style « Informations » qui t’explique ce que c’est les documents d’entreprises. => https://docs.preprod.camino.beta.gouv.fr/storybook/?path=/story/components-etape-edition--default

**Comment by pohayscamino** [comment]
ok merci

Je n'ai pas l'alerte "Informations"

https://preprod.camino.beta.gouv.fr/etapes/w-cx-chassiron-b-2003-pro01-mfr01/edition

L'autre c'est ok

**Comment by vmaubert** [comment]
T’avais un peu raison dans ton commentaire supprimé.
D’après le code, l’aide est visible que si c’est une demande d’ARM et d’AXM.
Je trouve ça un peu bizarre comme condition.
