### ISSUE TITLE
bug(instruction) : mauvaise démarche après enregistrement

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1137]
Je suis sur le titre suivant : https://preprod.camino.beta.gouv.fr/etapes/s-cx-donges-2001-oct01-dpu01/edition

dans la démarche d'octroi

![Image](https://github.com/MTES-MCT/camino/assets/144020267/ce929718-ff15-4352-938e-398cd4098181)

je modifie l'étape de "Publication de décision au JORF" et j'appuie sur "enregistrer l'étape". Ça renvoie automatiquement à l'autre démarche.

![Image](https://github.com/MTES-MCT/camino/assets/144020267/bd2896a7-7fb9-4438-8d14-788ac0cff616)

Ce serait mieux que je reste sur la démarche sur laquelle j'ai fait une modification pour voir l'étape modifiée.

**Comment by MichaelBitard** [comment]
Corrigé avec la #1141

**Comment by pohayscamino** [comment]
Tu as raison. On reste comme ça pour le moment

**Comment by MichaelBitard** [comment]
Ça prenait quelques secondes à faire, ça partira en preprod avec les prochaines livraisons
