### ISSUE TITLE
feat(sécurité) : plan de remédiation du dashlord

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1151]

**Comment by pohayscamino** [comment]
Mettre en place les recommandations du dashloard pour répondre à l'engagement pris en réunion d'homologation sécurité

**Comment by MichaelBitard** [comment]
Pour le `X-Content-Type-Options Header Missing`, c'est compliqué à mettre en place, c'est le robots.txt qui est géré par oauth2_proxy et soit:
- il faut configurer le nginx-proxy pour que ça soit lui qui rajoute ces headers (via nginx.tmpl que je préfère ne pas toucher)
- il faut activer la configuration alpha de oauth2_proxy pour rajouter les bons headers
