### ISSUE TITLE
feat(instruction) : permettre de supprimer un document déposé

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1171]

**Comment by pohayscamino** [comment]
Dans le titre suivant : https://camino.beta.gouv.fr/etapes/m-pr-brevenne-2023-oct01-ppu01/edition?zoom=5&centre=46.22545288226939&centre=2.5048828125000004&perimetre=2.5048828125000004&perimetre=46.22545288226939&perimetre=2.5048828125000004&perimetre=46.22545288226939&vueId=carte

J-R avait déposé maladroitement trop de documents dans l'étape de consultation du public. Ni lui ni moi (en super) ne pouvions les supprimer.

Il faudrait que ceux qui peuvent modifier puissent aussi supprimer.

**Comment by pohayscamino** [comment]
A besoin d'avoir fait la journalisation des évènements du ticket #1152

**Comment by pohayscamino** [comment]
Il y a eu une erreur dans mon ticket. Il ne faut pas limiter aux super. Il faudrait que tous ceux qui peuvent modifier puissent aussi supprimer.

**Comment by MichaelBitard** [comment]
Il me semble qu'on en avait parlé de ça justement et que ça pouvait poser des problèmes, genre un titulaire qui supprime des documents une fois la recevabilité faite. C'est pour ça que t'avais limité aux super

**Comment by pohayscamino** [comment]
aie aie aie j'ai mal précisé mon ticket. Merci pour l'alerte. Voici ma demande : 

Il ne faut pas limiter aux super. Il faudrait que tous ceux qui peuvent modifier puissent aussi supprimer. Sauf les titulaires qui ne peuvent jamais modifier une étape déposée.

**Comment by pohayscamino** [comment]
non ce ticket n'est pas totalement terminé. C'est pour ça que je l'avais gardé dans l'autre colonne.

Il faut ouvrir la suppression aux administration éditrices " Il faudrait que tous ceux qui peuvent modifier le document puissent aussi le supprimer. Sauf les titulaires qui ne peuvent jamais modifier une étape déposée."

**Comment by MichaelBitard** [comment]
Changement de spec alors que la tache est terminée :scream: 

On devrait refaire un contrat pour ça :smile:
