### ISSUE TITLE
bug(instruction) : Titre plus éditable

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1185]

**Comment by pohayscamino** [comment]
J'étais en train de travailler sur un titre compliqué de la DGEC : https://camino.beta.gouv.fr/titres/92a68218c21f86b43b7d21ce

J'avais fait une demande d'octoir et l'avais déposée. Néanmoins il manquait le périmètre.
J'ai ensuite créé la démarche de mutation. Et tout à buggé

**Comment by vmaubert** [comment]
@pohayscamino On peut fermer ?

**Comment by pohayscamino** [comment]
oui car sera traité dans ticket #1186
