### ISSUE TITLE
bug(perimetre) : Passer en UTF-8

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1193]

**Comment by pohayscamino** [comment]
https://camino.beta.gouv.fr/titres/g-px-zac-presqu-ile-grenoble-2016?demarcheSlug=g-px-zac-presqu-ile-grenoble-2016-mut01

![Image](https://github.com/MTES-MCT/camino/assets/144020267/8443db6a-2269-42f4-921b-514a5340a5c7)

**Comment by pohayscamino** [comment]
Pour lui c'est bon : https://preprod.camino.beta.gouv.fr/titres/g-pr-strasbourg-2013?demarcheSlug=g-pr-strasbourg-2013-pr201

mais pour lui c'est toujours pas bon : https://preprod.camino.beta.gouv.fr/titres/g-px-zac-presqu-ile-grenoble-2016?demarcheSlug=g-px-zac-presqu-ile-grenoble-2016-mut01

Je pense que vous n'avez mis l'UTF8 que pour les tableaux des périmètres. Il faut aussi le mettre sur les tableaux des forages.

**Comment by MichaelBitard** [comment]
Alors, les endroits ou c'est déjà cassé ça reste cassé. C'est juste que tu ne peux plus mettre à jour avec des accents cassés maintenant. On n'a pas oublié les forages.

T'es en train de dire que t'arrives encore à introduire des caractères cassés sur l'import des forages ?

**Comment by pohayscamino** [comment]
ok ok. Je n'avais pas en tête que ce qui était cassé restait cassé. 

J'ai déposé un nouveau fichier et c'est bon.
