### ISSUE TITLE
feat(instruction) : Permettre de déposer des fichiers supplémentaires partout

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1194]

**Comment by vmaubert** [comment]
> Il faut un champs nommé "nom" en dessous du type de document. Ce champs a le même design que le champ description. Il est obligatoire

On est moyen chaud pour cette partie. Est-ce que si on rend le champ `description` obligatoire dans le cas du `Autre document`, ça ne suffirait pas ?

**Comment by vmaubert** [comment]
À faire lors de la sélection de `Autre document` : 
- Champ `description` obligatoire
- Bouger le champ `description` juste en dessous du `Type de document`
