### ISSUE TITLE
feat(geothermie) : Terminer la machine de la procédure simplifiée

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1204]
Pour terminer la machine des PEX géothermie : 
- il faut rendre la machine ISO avec cet arbre d'instruction. (une étape à remplacer pour la publication, la visibilité du titre , le statut des démarches etc) : https://drive.google.com/file/d/16lXyw3pcuiP-rHkBBM0U2Al9sWHKCBP9/view
- il faut mettre la machine pour toutes les démarches (pas que l'octroi)
- pour l'octroi il y a une procédure complexe basée sur un arbre d'instruction (on garde) mais pour les autres comme il n'y a pas d'arbre je propose qu'on ne garde que la procédure simplifiée.

**Comment by MichaelBitard** [comment]
@pohayscamino on est allé un peu plus loin dans cette PR au final:

On a nettoyé l'ancien logigramme des Octrois de PER
On a crée les procédures historiques
Toutes les démarches de PEX Géothermies avant le 01/07/2024 sont en procédures historiques, les nouvelles seront en simplifiées.

Bonne recette

**Comment by pohayscamino** [comment]
dans le titre : https://preprod.camino.beta.gouv.fr/titres/g-px-test-pex-g-ara-2023?demarcheSlug=g-px-test-pex-g-ara-2023-oct01

Je ne peux que faire l'étape de dépôt (avant l'étape deja faite de décision). Or au vu du logigramme je devrais aussi avoir le droit de faire l'étape d'ouverture de la participation (avant l'étape deja faite de décision).

**Comment by MichaelBitard** [comment]
> dans le titre : https://preprod.camino.beta.gouv.fr/titres/g-px-test-pex-g-ara-2023?demarcheSlug=g-px-test-pex-g-ara-2023-oct01
> 
> Je ne peux que faire l'étape de dépôt (avant l'étape deja faite de décision). Or au vu du logigramme je devrais aussi avoir le droit de faire l'étape d'ouverture de la participation (avant l'étape deja faite de décision).

C'est toujours le même souci @pohayscamino. Tu ne peux **pas** faire l'étape d'ouverture parce qu'il **faudrait** avoir une étape de fermeture **puis** la décision de l'administration.

**Comment by pohayscamino** [comment]
aaah oui ok. Ca fonctionnera donc bien le jour où on aura fusionné les deux étapes de consultation du public.

Il reste quand même le souci sur les status

**Comment by MichaelBitard** [comment]
Oui bien vu le second souci, c'est à cause de l'ancien TDE, on est en train de corriger ça dans la PR 1315
