### ISSUE TITLE
feat(inscription) : permettre de visualiser le mdp lors de l'inscription

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1213]

**Comment by vmaubert** [comment]
où ? Ça me paraît d’être une mauvaise idée :-)

**Comment by pohayscamino** [comment]
sur la page de connection. Ici : 

![image](https://github.com/MTES-MCT/camino/assets/144020267/3a2a49e9-4758-4b54-96e6-0899bbbb786e)

Mais c'est peut être une mauvaise idée.

**Comment by vmaubert** [comment]
Ok j’ai compris.
J’ai pas envie de prendre de risque, et là c’est du keycloak…
Je propose qu’on ne le fasse pas, et ce pb peut éventuellement embêter l’utilisateur que une seule fois.

**Comment by pohayscamino** [comment]
ok
