### ISSUE TITLE
feat(droits) : Ouvrir les droits d'éditeurs des ARM à la DGTM

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1245]
L'ONF ne sera plus instructreur des procédures d'ARM à partir de la réforme. Nous devons dès maintenant ouvrir les mêmes droits à la DGTM que ceux de l'ONF et du PTMG, pour les AR-M.

La DGTM pourra alors modifier toutes les étapes.

**Comment by vmaubert** [comment]
Pour résumer, on donne TOUS les droits à la DGTM pour les ARM ?

**Comment by pohayscamino** [comment]
oui
