### ISSUE TITLE
bug(API) : supprimer la doc API

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1246]
les URL suivantes devraient me permettre de récupérer les feature collections des démarches et des activités mais à la place elle m'exportent des csv

https://api.camino.beta.gouv.fr/demarches?
https://api.camino.beta.gouv.fr/activites?

**Comment by MichaelBitard** [comment]
Alors, nos api ne sont pas documentées, on n'a aucune garantie dessus AMHA.

Il faut faire attention aux routes qui ne commencent pas par '/rest/' parce que ce sont des anciennes routes utilisées notamment pour les téléchargements (csv, xlsx, json).

On essaie de ne pas trop y toucher parce que elles sont potentiellement référencées par d'autre outils.

**Comment by pohayscamino** [comment]
Pas sur de comprendre. J'ai suivi ce qui est indiqué dans notre documentation : https://docs.camino.beta.gouv.fr/01-utilisation/03-rest/#essayer-une-api-rest

On en reparle à notre prochaine réunion hebdo

**Comment by MichaelBitard** [comment]
Ho wow, je ne savais pas que ça existait cette doc hahaha....

**Comment by pohayscamino** [comment]
Vérifier qu'il n'y a rien dans la doc qui soit primordial pour les utilisateurs. S'il n'y a rien, détruisez tout. :)

**Comment by pohayscamino** [comment]
je ne sais pas comment tester en preprod

**Comment by pohayscamino** [comment]
ok merci. Mais je la vois toujours. Vous ne l'avez pas supprimée.

**Comment by MichaelBitard** [comment]
Moi je ne la vois plus non plus
