### ISSUE TITLE
feat(instruction) : Passer tous les titres du domaine C dans la procédure simplifiée

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1299]
Passer tous les titres C en procédure simplifiée . 

La date à utiliser pour l'historique est la même que pour les permis G deja en procédure simplifiée.

Il faut me lister les titres anciens qui n'entreraient pas dans la procédure simplifiée.

Le tableau des démarches est ici (onglet "démarches_machines") : https://docs.google.com/spreadsheets/d/11sKxZp57c5FBRLU2ceZvbJGsSuyGVnK4/edit?gid=1194142650#gid=1194142650

**Comment by anis** [comment]
Hello @pohayscamino ,

Plusieurs cas qui posent problème, mais en quantité raisonnable (8), les voici :
- plusieurs publications au JORF : https://camino.beta.gouv.fr/titres/c-pc-cormeilles-en-parisis-1965?demarcheSlug=c-pc-cormeilles-en-parisis-1965-oct01
- plein d'étapes non prévues 🤷🏼‍♂️ : 
  - https://camino.beta.gouv.fr/titres/c-pc-glomel-1972?demarcheSlug=c-pc-glomel-1972-pro04
  - https://camino.beta.gouv.fr/titres/c-pc-cormeilles-en-parisis-1965?demarcheSlug=c-pc-cormeilles-en-parisis-1965-pro06
  - https://camino.beta.gouv.fr/titres/c-pc-poses-lery-1975?demarcheSlug=c-pc-poses-lery-1975-pro04
  - https://camino.beta.gouv.fr/titres/c-pc-larchant-1972?demarcheSlug=c-pc-larchant-1972-pro05
  - https://camino.beta.gouv.fr/titres/c-pc-brueil-en-vexin-2019?demarcheSlug=c-pc-brueil-en-vexin-2019-oct01
  - https://camino.beta.gouv.fr/titres/c-pc-berrien-1972?demarcheSlug=c-pc-berrien-1972-pro04
  - https://camino.beta.gouv.fr/titres/c-pc-berrien-1972?demarcheSlug=c-pc-berrien-1972-mut02

**Comment by pohayscamino** [comment]
Normalement avec la dernière version de l'arbre et les corrections manuelles que j'ai fait ça devrait être ok. Est-ce que tu peux me ressortir la liste après avoir pris en compte le nouvel arbre?

**Comment by vmaubert** [comment]
@pohayscamino  Il reste ces 2 là :

- https://camino.beta.gouv.fr/titres/c-pc-cormeilles-en-parisis-1964?demarcheSlug=c-pc-cormeilles-en-parisis-1964-pro07
- https://camino.beta.gouv.fr/titres/c-pc-cormeilles-en-parisis-1964?demarcheSlug=c-pc-cormeilles-en-parisis-1964-pro06

**Comment by pohayscamino** [comment]
ok c'est corrigé

**Comment by vmaubert** [comment]
@pohayscamino il reste toujours celle-ci => https://camino.beta.gouv.fr/titres/c-pc-cormeilles-en-parisis-1964?demarcheSlug=c-pc-cormeilles-en-parisis-1964-pro06

**Comment by pohayscamino** [comment]
C'est corrigé

**Comment by pohayscamino** [comment]
Quand je crée une étape on m'en propose beaucoup trop par rapport au logigramme simplifié : https://camino.beta.gouv.fr/etapes/creation?demarche-id=c-ap-test-app-c-0000-oct01



![Image](https://github.com/user-attachments/assets/e14eea28-2916-455c-9ec9-ee9a56c9b3c3)
