### ISSUE TITLE
feat(instruction) : Passer tous les titres du domaine F en procédure simplifiée.

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1300]
La date à utiliser pour l'historique est la même que pour les permis G deja en procédure simplifiée.

Il faut me lister les titres anciens qui n'entreraient pas dans la procédure simplifiée.

Le tableau des démarches est ici (onglet "démarches_machines") : https://docs.google.com/spreadsheets/d/11sKxZp57c5FBRLU2ceZvbJGsSuyGVnK4/edit?gid=1194142650#gid=1194142650

**Comment by anis** [comment]
Hello @pohayscamino ,

On a un seul type type d'erreur cette fois, mais qui arrive plusieurs dizaines de fois : des titres avec une seule étape, une publication au JORF (cas non prévu par le logigramme des procédures simplifiées pour le moment).

Quelques exemples :
- https://camino.beta.gouv.fr/titres/f-cx-longeville-1920?demarcheSlug=f-cx-longeville-1920-oct01
- https://camino.beta.gouv.fr/titres/f-cx-lauterbacherhof-iii-1810?demarcheSlug=f-cx-lauterbacherhof-iii-1810-oct01

**Comment by pohayscamino** [comment]
Problème déjà rencontré dans le ticket #1301 et normalement résolu avec les modifications de l'arbre d'instruction
