### ISSUE TITLE
Passer tous les titres du domaine R en procédure simplifiée.

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1301]
La date à utiliser pour l'historique est la même que pour les permis G deja en procédure simplifiée.

Il faut me lister les titres anciens qui n'entreraient pas dans la procédure simplifiée.

Le tableau des démarches est ici (onglet "démarches_machines") : https://docs.google.com/spreadsheets/d/11sKxZp57c5FBRLU2ceZvbJGsSuyGVnK4/edit?gid=1194142650#gid=1194142650

**Comment by anis** [comment]
Hello,

On rencontre pas mal de titres qui ne respectent pas le logigramme de la procédure simplifiée.
Voici les cas que l'on a pu recenser :

- https://camino.beta.gouv.fr/titres/r-pr-previnquieres-1958?demarcheSlug=r-pr-previnquieres-1958-pr101 : deux publications au JORF pour corriger l'engagement => quelques unes
- https://camino.beta.gouv.fr/titres/r-in-bea-1810?demarcheSlug=r-in-bea-1810-oct01 : etape type 'ihi' (informations historiques incomplètes) => beaucoup
- https://camino.beta.gouv.fr/titres/r-pr-curan-1975?demarcheSlug=r-pr-curan-1975-oct01 : uniquement une publication au JORF => beaucoup
- https://camino.beta.gouv.fr/titres/r-pr-meslan-1958?demarcheSlug=r-pr-meslan-1958-oct01 : publication au JORF après une décision rejetée => quelques unes
- https://camino.beta.gouv.fr/titres/r-cx-lachaux-1929?demarcheSlug=r-cx-lachaux-1929-mut01 : publication au JORF AVANT et APRÈS décision de l'administration => une ou deux

**Comment by pohayscamino** [comment]
J'ai mis à jour l'arbre d'instruction (un peu complexifié...) et j'ai fait les corrections manuelles pour que ça fonctionne. Vous pouvez refaire la liste suite à modification de la machine?

Je vous remets le lien vers l'arbre ici : https://drive.google.com/drive/u/1/folders/1U_in35zSb837xCp_fp31I0vOmb36QguL

**Comment by pohayscamino** [comment]
je ne comprends pas bien. Dans ce titre : https://preprod.camino.beta.gouv.fr/titres/r-cx-test-concession-r-2011?demarcheSlug=r-cx-test-concession-r-2011-oct01

J'ai pu créer l'étape de décision de l'administration alors que la demande est encore en brouillon. Par contre je ne peux pas créer l'étape de publication au JORF

De plus je ne peux pas la déposer via le bouton de l'étape : 


![Image](https://github.com/user-attachments/assets/c139f96b-61c4-43aa-8c13-83a6f28298b9)

Mais si je l'ouvre, sans rien modifier, le bouton pour déposer est bien cliquable


![Image](https://github.com/user-attachments/assets/c0d14519-22dc-451f-b8c1-bf4545341029)
