### ISSUE TITLE
bug(instruction) : Mauvais statut pour la lettre de saisine des services

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1305]
Dans la nouvelle étape "Avis des services et commissions consultatives" la "Lettre de saisine des services" doit avoir le statut de type "fait"

**Comment by MichaelBitard** [comment]
Donc on ne saisit plus le statut de l'avis dans le cas de la "Lettre de saisine des services", son statut est à "fait" automatiquement

**Comment by vmaubert** [comment]
@pohayscamino on l'a fait, mais après réflexion on se pose une question !
Ça n'a vraiment pas l'air d'être un avis, alors pourquoi on ne le met pas dans les documents obligatoires de l'étape ?

On aurait 2 tableaux, 1 pour les documents et 1 pour les avis.

**Comment by vmaubert** [comment]
@pohayscamino fausse bonne idée, car le document n'est pas présent 79 fois en prod. 
Donc on ne peut pas le mettre en document obligatoire, à part si tu souhaites rendre cette étape incomplète 79 fois en prod.

**Comment by vmaubert** [comment]
@pohayscamino ou on peut aussi mettre un doc vide (ou autre) sur ces 79 étapes, et rendre la lettre obligatoire pour toutes les futures étapes

**Comment by pohayscamino** [comment]
[fichier vide.pdf](https://github.com/user-attachments/files/16262462/fichier.vide.pdf)

**Comment by vmaubert** [comment]
@pohayscamino C'est un des types de documents suivant, ou faut en ajouter un nouveau ? 

 lac: { id: 'lac', nom: "Lettre de saisine des services de l'administration centrale" },
  lce: { id: 'lce', nom: "Lettre de saisine du conseil d'Etat" },
  lcg: { id: 'lcg', nom: "Lettre de saisine du conseil général de l'économie (CGE)" },
  lcm: { id: 'lcm', nom: 'Lettre de saisine des services civils et militaires' },
  lem: { id: 'lem', nom: 'Lettre de demande' },
  let: { id: 'let', nom: 'Lettre' },
  lpf: { id: 'lpf', nom: 'Lettre de saisine du préfet' },

**Comment by pohayscamino** [comment]
c'est celui-là
lcm: { id: 'lcm', nom: 'Lettre de saisine des services civils et militaires' },
