### ISSUE TITLE
feat(instruction) : Créer deux nouveaux statuts pour la démarche simplifiée

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1308]
Reprendre les indications du logigramme de la démarche simplifiée : https://drive.google.com/file/d/16lXyw3pcuiP-rHkBBM0U2Al9sWHKCBP9/view

Mettre à jour la partie sur la publication (statut des étapes et de la démarche)

Mettre à jour la partie sur le rejet de la décision de l'administration

**Comment by vmaubert** [comment]
vérifier pourquoi ce titre n'est pas rejeté et publié 
https://preprod.camino.beta.gouv.fr/titres/h-pr-montelimar-2010?demarcheSlug=h-pr-montelimar-2010-oct01

**Comment by vmaubert** [comment]
> vérifier pourquoi ce titre n'est pas rejeté et publié https://preprod.camino.beta.gouv.fr/titres/h-pr-montelimar-2010?demarcheSlug=h-pr-montelimar-2010-oct01

@pohayscamino La démarche simplifiée est appliquée que pour le domaine G, alors que ce titre est dans le domaine H

**Comment by pohayscamino** [comment]
je ne l'avais peut être pas encore ajouté mais il faudrait une publication au JORF après le rejet. Cette étape ne modifie pas le statut de la démarche. Il y a des anciens titres avec cette étape.

**Comment by vmaubert** [comment]
Ha oui t'as tout changé le logigramme. 
C'est prioritaire ? Faut faire ça avant de mettre en prod.

**Comment by pohayscamino** [comment]
non c'est nécessaire uniquement pour arriver à gérer tous les domaines. On peut faire ça par étape
