### ISSUE TITLE
feat(instruction) : Avertir de la suppression automatique des démarches de travaux

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1313]
lié au ticket #1292 

dans ce titre : https://preprod.camino.beta.gouv.fr/titres/w-cx-baie-de-seine-2013?demarcheSlug=w-cx-baie-de-seine-2013-oct01

J'ai supprimé l'étape de publication. Les travaux ont disparus automatiquement. Il faudrait quand même un message d'alerte (comme pour les dépôts par exemple) qui prévienne l'utilisateur que toutes ses démarches de travaux seront supprimées, et qu'il valide.

**Comment by vmaubert** [comment]
@pohayscamino non, tu peux retrouver tes travaux dans la page « Travaux »

**Comment by pohayscamino** [comment]
ah ouais énorme en fait c'est pas supprimé et quand je refais la publication ils réapparaissent dans la frise. Trop trop bien.
