### ISSUE TITLE
feat(simplifications) : fusionner les étapes de participation du public

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1316]
Que pour la procédure simplifiée : 
Fusionner les deux étapes suivante dans une étape nommée "Participation du public".

![Image](https://github.com/MTES-MCT/camino/assets/144020267/a62a0a1b-04a4-4085-9445-365b569be119)

Il faut demander la date de début et durée de la participation.

Il faut les 3 statuts suivants (qui n'apparaissent que quand on n'est plus en mode brouillon) : 
- "programmé" (avant date de début)
- "en cours" (entre date de début et date de fin)
- "terminé" (après date de fin)

L'étape ne devient visible qu'au statut en cours

**Comment by pohayscamino** [comment]
Le logigramme à jour : https://drive.google.com/file/d/16lXyw3pcuiP-rHkBBM0U2Al9sWHKCBP9/view

**Comment by vmaubert** [comment]
@pohayscamino Nous avons des pbs avec ces titres suivants :
  - http://camino.beta.gouv.fr/demarches/3LErsZZBdLsL0td915Gln7Fn // elle a une ouverture de ENQUÊTE publique et une fermeture de la PARTICIPATION du public
  - http://camino.beta.gouv.fr/demarches/AMyAuvVJ8Y1fHknlnyhxKK3L  // pas d'ouverture
  - http://camino.beta.gouv.fr/demarches/a8fxkB5t7VvSvAAGTA5FS9cZ // pas d'ouverture
  - http://camino.beta.gouv.fr/demarches/me1HK9RyOgKcbQSTYizLn1KB // pas d'ouverture
  - http://camino.beta.gouv.fr/demarches/tZcNoZimGRDE7AOLSk8TJVqH  // pas d'ouverture

**Comment by vmaubert** [comment]
On ne peut pas rejeter si la ppu n'est pas terminée

**Comment by pohayscamino** [comment]
Les titres sont corrigés
