### ISSUE TITLE
bug(filtres) : mauvais filtre selectionné

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1353]
Dans l'onglet démarches, j'essaie de sélectionner le filtre "fin de police des mines" mais ça me sélectionne "permis exclusif de recherche).

J'arrive à le sélectionner quand j'appuie sur le mont mais pas quand j'appuie sur la case

![Image](https://github.com/user-attachments/assets/b082b83d-ae90-4b79-9935-d96628be39f8)

**Comment by MichaelBitard** [comment]
Ça le fait encore ? Parce que je n'arrive pas à le reproduire ce bug.

Tu viens nous le montrer @pohayscamino  ?

**Comment by pohayscamino** [comment]
j'ai réessayé et ça ne le fait plus
