### ISSUE TITLE
bug(instruction) : Le titulaire n'est plus automatiquement complété dans la demande

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1358]
On me demande le nom du titulaire quand je demande le titre mais après il n'apparait pas sur le titre indéterminé ni dans mon formulaire de demande.

Soit on le remet automatiquement, soit on ne le demande plus lors de la création du titre.

L'autre problème c'est que j'ai donc pu créer et déposer une demande sans mettre de titulaire. On a des titres sans titulaires? Peut être dans vieux titres....

**Comment by MichaelBitard** [comment]
> On me demande le nom du titulaire quand je demande le titre mais après il n'apparait pas sur le titre indéterminé ni dans mon formulaire de demande.

Oui, c'est dû au fait que maintenant, on ne crée plus automatiquement l'étape... je fais la PR pour virer la demande du titulaire dans ce cas là


> L'autre problème c'est que j'ai donc pu créer et déposer une demande sans mettre de titulaire. On a des titres sans titulaires? Peut être dans vieux titres....

Alors, un titulaire/amodiataire est **obligatoire** seulement is il y'a des documents d'entreprises **obligatoires**.

Et si tu regardes ce fichier ligne 36 --> https://github.com/MTES-MCT/camino/blob/master/packages/common/src/static/titresTypes_demarchesTypes_etapesTypes/entrepriseDocuments.ts#L36

Tu peux voir tous les cas où il y'a des documents d'entreprise obligatoires.

Par exemple pour une **demande** d'**octroi** d'**ARM**, le kbis (et tous les autres) sont obligatoires donc tu ne peux **pas** déposer la demande sans titulaire.

**Comment by pohayscamino** [comment]
vous pourriez me sortir le nombre de titres qui n'ont pas de titulaires svp?

**Comment by MichaelBitard** [comment]
`select count(*) from titres where not props_titre_etapes_ids ? 'titulaires' and archive is false;`

Il y'en a 561 !
