### ISSUE TITLE
debugg(instruction) : ajouter de l'étape "publication dans un journal local ou national" dans TDE

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#1397]
Le faire pour les prolongations 1, prolongation 2 de PR-M

**Comment by vmaubert** [comment]
@pohayscamino les étapes pour les prolongations de PRM sont les mêmes que pour les granulats marins.
Je peux aussi ajouter cette étape aux granulats marins ?

**Comment by pohayscamino** [comment]
oui aussi pour les W stp
