### ISSUE TITLE
feat(simplification): wrd devient apd

### ISSUE THREAD

**Issue by anis** [MTES-MCT/camino#1457]
Lié à #1416

- rapportDeLaDreal (wrd) devient avisEtRapportDuDirecteurRegionalChargeDeLenvironnementDeLamenagementEtDuLogement (apd)

**Comment by pohayscamino** [comment]
vous pourriez renommer apd en avisEtRapportDuDREAL

**Comment by pohayscamino** [comment]
ce serait possible de fusionner les documents : "Rapport de l’administration centrale chargé des mines" et "Rapport" dans "Rapport de la direction régionale chargée des mines"?

Vous pourriez juste mes donner des exemples de titres avec des "Rapport de l’administration centrale chargé des mines"?
