### ISSUE TITLE
feat(dsfr): le pied de page respecte le Système de Design de l'État

### ISSUE THREAD

**Issue by MichaelBitard** [MTES-MCT/camino#317]
_**Nouveau Footer :**_

![Image](https://user-images.githubusercontent.com/414642/211290816-348610a6-73cc-4f31-8602-87d4fa16b190.png)

\*\*Section 1 / Menu : \*\*

- Aux normes DSFR
- Renvoyant vers les liens du Gitbook

**- Colonnes 1 : Contact**

- Nous contacter (URL : [https://camino.gitbook.io/guide-dutilisation/a-propos/contact](https://camino.gitbook.io/guide-dutilisation/a-propos/contact "‌"))
- À propos (URL : [https://camino.beta.gouv.fr/a-propos](https://camino.beta.gouv.fr/a-propos "‌"))

**- Colonne 2 : Utiliser Camino**

- Glossaire (URL : [https://camino.gitbook.io/guide-dutilisation/camino/glossaire](https://camino.gitbook.io/guide-dutilisation/camino/glossaire "‌"))
- Tutoriel (URL : [https://camino.gitbook.io/guide-dutilisation/camino/guide-dutilisation](https://camino.gitbook.io/guide-dutilisation/camino/guide-dutilisation "‌"))
- API (URL : [https://docs.camino.beta.gouv.fr/](https://docs.camino.beta.gouv.fr/ "‌"))

**- Colonne 3 : Indicateurs**

- Statistiques (URL : [https://camino.beta.gouv.fr/statistiques/globales](https://camino.beta.gouv.fr/statistiques/globales "‌"))

**- Colonne 4 : Liens externes / Autres**

- Minergies (URL : [http://www.minergies.fr/](http://www.minergies.fr/ "‌"))
- MineralInfos (URL : [http://www.mineralinfo.fr/](http://www.mineralinfo.fr/ "‌"))

\*\*Section 2 / Logo & Refs. : \*\*

- Ajouter les deux logos
- Les noms des Ministères et URLs

\*\*Section 3 / CGU / Mentions Légales / Accessibilités \*\*

_**Autres tâches :**_
Suppression/Cacher des pages en code dans le site :

- Glossaire,
- CGU,
- Mentions légales
- Contact

‌

**Comment by vmaubert** [comment]
@annalouisbeta Il n'y a pas de lien gitbook pour l'accessibilité ?

**Comment by patrick-produit** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [mise en place du DSFR](https://trello.com/c/XI4WAhk2/15-mise-en-place-du-dsfr)
