### ISSUE TITLE
feat(démarche): ajouter les étapes manquantes à la prolongation d’AXM

### ISSUE THREAD

**Issue by vmaubert** [MTES-MCT/camino#361]
Il manque beaucoup d’étapes actuellement.
Il faut surement mettre une nouvelle machine sur cette démarche.
[m-aex-pro-prolongation.pdf](https://github.com/MTES-MCT/camino/files/10447601/m-aex-pro-prolongation.pdf)

**Comment by patrick-produit** [comment]
KO après la "saisine des collectivités locales" et la "saisine des services", je ne me vois pas proposer l'étape obligatoire suivante "avis du DREAL, DEAL ou DGTM"



![Image](https://user-images.githubusercontent.com/82831061/234242134-1127341b-ae14-4bd8-8372-83e864462c2d.png)



![Image](https://user-images.githubusercontent.com/82831061/234242284-95f673bd-81d0-4e9f-8cae-0de366b10bbf.png)



![Image](https://user-images.githubusercontent.com/82831061/234242361-e0427e6a-ff2b-4ac8-a4c2-f60e5c58827a.png)
