### ISSUE TITLE
chore(infra): install la dernière version de postgre

### ISSUE THREAD

**Issue by MurielNouguier** [MTES-MCT/camino#395]
Suite à une faille sur PostgreSQL, il est nécessaire de monter en version:
https://www.cert.ssi.gouv.fr/avis/CERTFR-2023-AVI-0107/

**Comment by MichaelBitard** [comment]
On a la version `(PostgreSQL) 12.10 (Debian 12.10-1.pgdg110+1)` à l'heure actuelle

Il faut qu'on migre vers une version supérieure à `12.14`

Ou en profiter pour migrer vers 13, 14 ou 15.

En tout cas il faut être au dessus de 
```
    PostgreSQL versions 15.x antérieures à 15.2
    PostgreSQL versions 14.x antérieures à 14.7
    PostgreSQL versions 13.x antérieures à 13.10
    PostgreSQL versions 12.x antérieures à 12.14
    PostgreSQL versions 11.x antérieures à 11.19

```
