### ISSUE TITLE
Affichage des étiquettes des titres miniers;

### ISSUE THREAD

**Issue by MurielNouguier** [MTES-MCT/camino#402]
pouvoir afficher les étiquettes des titres miniers;

**Comment by vmaubert** [comment]
Je ne suis pas certain de comprendre, @LimamAh peux-tu te renseigner à propos de cette demande stp.

**Comment by patrick-produit** [comment]
Le besoin : 

- lorsque j'ai plusieurs résultats sur la carte, je veux visualiser les informations (nom du titre, commune...) simultanément
- or, je suis obligé de passer au survol sur chaque titre un à un pour voir les infos

- idéalement : lorsque j'ai plusieurs résultats sur la carte, je veux visualiser les informations (nom du titre, commune...) simultanément
- en réalité, je suis obligé de passer au survol sur chaque titre un à un pour voir les infos
- en conséquence, je perds du temps et ce n'est pas pratique
- proposition de solution : 
  - refondre la carte et la liste de résultats => investigation design

Conclusion : le ticket passe dans le backlog UX
