### ISSUE TITLE
feat(données): télécharge les données spatiales au format shape

### ISSUE THREAD

**Issue by MurielNouguier** [MTES-MCT/camino#403]
pouvoir télécharger dans un format SIG classique (shapefile .shp) utilisé notamment part le logiciel QGIS préconisé par le socle interministériel de logiciels libres ;

**Comment by vmaubert** [comment]
Peut-être utiliser https://github.com/jdesboeufs/geojson2shp

**Comment by MichaelBitard** [comment]
Ça fait une dépendance pas forcément triviale à rajouter (et lourde).

Nous sommes déjà compatibles avec le logiciel QGIS via les GEOJSON, et même directement via notre API, et le plugin CAMINO_QGIS.

Je propose de ne pas faire cette tache @MurielNouguier

**Comment by MichaelBitard** [comment]
> aussi, c'est un détail mais de mémoire un titre rentré récemment dans Camino n'était pas dans QGIS
> Quelle est la fréquence d'actualisation des données ? du call API de QGIS vers Camino ?

Si le titre n'est pas publique, et qu'il ne s'est pas loggé avec l'extension camino, alors c'est normal qu'il ne le voie pas.
Il y'a une procédure pour générer un token côté camino afin de pouvoir être authentifié et récupérer les titres auxquels on a le droit.

Ok pour le bug dans l'extension, il va falloir la faire évoluer.

Il peut aussi en attendant, pour le débloquer, télécharger les titres au format geojson depuis camino, et les utiliser dans QGIS

**Comment by patrick-produit** [comment]
il parait que c'est compliqué d'importer le geojson dans QGIS
il pensait avoir essayé et que ça marchait pas, mais il vient de tester et c'est bon ! 

par contre ça manque d'info dans un format geojson (exemple : il manque date d'attribut) donc ça serait beaucoup plus pratique pour lui si les filtres dans le plugins fonctionnent

je te laisse faire le ticket au core dev et l'utilisateur a une solution intermédiaire en attendant 
donc pas de dev de notre part !

**Comment by patrick-produit** [comment]
- améliorer les metadata du geojson
- améliorer la doc pour utiliser l'API et récupérer directement la route API

**Comment by vmaubert** [comment]
Merci
