### ISSUE TITLE
feat(doc): le schéma d'architecture de camino est à jour

### ISSUE THREAD

**Issue by MichaelBitard** [MTES-MCT/camino#454]

**Comment by patrick-produit** [comment]
https://docs.camino.beta.gouv.fr/03-architecture/01-introduction/

on parle de ce schéma ?

**Comment by MichaelBitard** [comment]
Non on parle de celui là : https://docs.preprod.camino.beta.gouv.fr/03-architecture/01-introduction/

Il n'est pas en prod encore ;)
