### ISSUE TITLE
fix(ui): le filtre "département" est plus clairement identifié comme une liste déroulante (Select) et indique les numéros de départements

### ISSUE THREAD

**Issue by patrick-produit** [MTES-MCT/camino#460]
1. le filtre de recherche "département" est plus clairement identifié comme une liste déroulante (Select)

https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/liste-deroulante

![Image](https://user-images.githubusercontent.com/82831061/226302305-bb317df9-03e4-4694-9c61-83f8e80c40b5.png)

- [ ] un chevron (vers le bas) indique qu'il s'agit d'une liste déroulante
- [ ] au clic, la liste apparaît ainsi que le curseur
- [ ] il est toujours possible de taper une requête

2. les numéros de départements apparaissent à côté du nom du département sous le format "Paris (75)"
![Image](https://user-images.githubusercontent.com/82831061/226302620-e41e7079-6ece-4cea-8e45-b10ca16026de.png)

- [ ] il est possible de rechercher par nom ou par numéro de département

**Comment by vmaubert** [comment]
@patrick-produit je n’ai pas fait `un chevron (vers le bas) indique qu'il s'agit d'une liste déroulante` car ça des impacts sur d’autres champs. Il y a un conflit entre ceux qui sont sous le DSFR et ceux qui ne le sont pas. Ça me donnait trop de temps pour faire ça correctement.
Ça sera fait ultérieurement avec l’arrivée du DSFR qui sera appliqué à tout le projet (pas besoin d’ouvrir d’issue)
