### ISSUE TITLE
fix(alert) : bug alerte sur page d'une administration

### ISSUE THREAD

**Issue by patrick-produit** [MTES-MCT/camino#472]
**Conditions de réplication :** 

1. En étant non-connecté, cliquer sur "annuaire" et sélectionner "administration"
2. cliquer sur n'importe quelle administration
3. visualiser le badge d'alerte "!" rouge au milieu de la page

![Image](https://user-images.githubusercontent.com/82831061/227567710-a84f359b-5b46-4c3c-aac9-ae37869f96f1.png)

**Comment by patrick-produit** [comment]
PS : est-ce qu'on souhaite que les permissions accordées à une administration soient visibles à tous ?

![Image](https://user-images.githubusercontent.com/82831061/227569455-a4c1abc1-f3bb-4774-9d4b-6481d0a372b6.png)

**Comment by vmaubert** [comment]
> PS : est-ce qu'on souhaite que les permissions accordées à une administration soient visibles à tous ?

@patrick-produit 
On peut les cacher (ou pas). Cette config est dans le code, le code est open source donc tout le monde peut voir les permissions dans le code. À toi de décider si c’est à cacher dans l’interface pour certains utilisateurs.
