### ISSUE TITLE
fix(QGIS): il manque le bouton pour valider son identifiant et son jeton API

### ISSUE THREAD

**Issue by patrick-produit** [MTES-MCT/camino#495]
Quasiment tout est dis dans le titre : 

- en tant qu'utilisateur
- je récupère mon jeton QGIS sur ma page de profil
- j'ouvre le plugin CAMINO sur QGIS et me rends dans l'onglet connexion
- je saisis mon email utilisateur camino dans le champ "identifiant"
- et mon jeton QGIS dans le champ "mot de passe"
- et... 🥁🥁🥁 je ne peux pas confirmer, il manque un bouton ou une sauvegarde des infos 😞

**Comment by vmaubert** [comment]
@patrick-produit Pour info le plugin QGIS n’est pas géré par l’équipe Camino. C’est un side project développé par un agent public. Voici son repo => https://github.com/MTES-MCT/camino-flux-QGIS

**Comment by MichaelBitard** [comment]
On ferme cette issue, pas liée à ce projet
