### ISSUE TITLE
feat(étape): mettre en avant les étapes manquantes pour aller jusqu’à la publication au JORF

### ISSUE THREAD

**Issue by vmaubert** [MTES-MCT/camino#504]
# Checklist

* [ ] Aller sur démarche d’AEX en cours d’instruction
* [ ] Cliquer sur Ajouter une étape
* [ ] Dans la liste des types d’étape, l’étape qui « est sur le chemin » pour d’aller vers la publication au JORF est en gras en 1ère position

# Pourquoi
Actuellement les utilisateurs doivent connaitre par cœur les cacoo pour faire avancer les démarches.

**Captures d'écrans/maquettes**
![Exemple où l’utilisateur ne sait pas quelle étape créer](https://user-images.githubusercontent.com/6149841/230012893-6da131a4-902d-4d34-8fe9-f782e74bc0f6.png)

**Comment by vmaubert** [comment]
@patrick-produit je viens de créer ce ticket suite à l’email de ce matin

**Comment by MichaelBitard** [comment]
celle là fait planter le front : https://preprod.camino.beta.gouv.fr/etapes/creation?demarche-id=m-ax-sud-affluent-crique-korossibo-amont-2022-oct01

celle là n'a rien en gras : https://preprod.camino.beta.gouv.fr/titres/m-ax-grand-marquis-2018

**Comment by MichaelBitard** [comment]
Haha pour celle là (https://preprod.camino.beta.gouv.fr/titres/m-ax-grand-marquis-2018) c'est "normal", il faut faire la demande 30 jours plus tard.
C'est pour ça qu'il n'y a rien en gras...
