### ISSUE TITLE
feat(ui): on peut voir les périmètres des titres "Valides" dans un calque sur le détail d'un titre

### ISSUE THREAD

**Issue by MichaelBitard** [MTES-MCT/camino#505]
# Checklist

* [ ] Aller sur le détail d'un titre
* [ ] Voir les périmètres des titres valides autour du titre par défaut, si celui ci a un périmètre
* [ ] Pouvoir désélectionner le calque

# Pourquoi
Afin que les utilisateurs puissent voir si il y'a des titres qui existent autour du leur

**Comment by vmaubert** [comment]
On ne fait pas le calque « Tous » car il y a trop de résultats.
