### ISSUE TITLE
fix(rights): impossible de supprimer un document d'une étape enregistrée

### ISSUE THREAD

**Issue by patrick-produit** [MTES-MCT/camino#516]
Une erreur se produit quand, en tant qu'agent public admin : 

1. j'édite une étape déjà enregistrée avec un ou des documents, 
![Image](https://user-images.githubusercontent.com/82831061/232505269-f3e537a7-59e7-4618-8081-71e50fa79165.png)

2. que je supprime un document 
![Image](https://user-images.githubusercontent.com/82831061/232505496-11d5942e-9c36-41a6-a21b-f304b14b6f04.png)

3. et que j'enregistre
![Image](https://user-images.githubusercontent.com/82831061/232505598-2923b156-0d8a-4920-94f0-6b54351b6d00.png)

"Erreur: error: droits insuffisants"

- [ ] permettre aux admins de supprimer un document sur une étape enregistrée

**Comment by MichaelBitard** [comment]
* [ ] Après l’enregistrement, il n’est pas possible de supprimer un document lié à une étape (donc de voir le bouton suppression)
* [ ] On peut supprimer un document (non obligatoire) juste avant d’enregistrer

**Comment by MichaelBitard** [comment]
Dans ton cas, tu ne verras plus le bouton supprimer du document, car en fait, tu n'avais pas le droit de le supprimer.
C'est ça que la PR corrige
