### ISSUE TITLE
feat(étape): quand on ajoute un document, initialiser la date à la date de l’étape

### ISSUE THREAD

**Issue by vmaubert** [MTES-MCT/camino#520]
- [ ] : Ajouter une étape dans le passée sur un titre
- [ ] : Ajouter un document à cette étape
- [ ] : Par défaut la date est initialisée à la date de l’étape

**Comment by patrick-produit** [comment]
OK pour ajout doc

mais KO quand doc créé automatiquement car obligatoirement lié à étape :


![Image](https://user-images.githubusercontent.com/82831061/234234099-3b7dbe77-4e4a-43f6-950f-4043f9f510fd.png)
