### ISSUE TITLE
ajouter les substances "dioxyde de carbone (CO₂)" et "hydrogène (H)" au domaine "stockage souterrain"

### ISSUE THREAD

**Issue by patrick-produit** [MTES-MCT/camino#585]
https://matrix.to/#/!YAHYlwUZtOTEycSOFg:agent.dinum.tchap.gouv.fr/$DhHX5FePsrqSRYILzrcxfoXST4jxg_vxk5UBJo4OZsM?via=agent.dinum.tchap.gouv.fr&via=agent.dev-durable.tchap.gouv.fr

faire apparaître "dioxyde de carbone (CO₂)" et "hydrogène (H)" dans la liste des substances des titres de PER et concession du domaine stockage sous-terrain S.

Comment tester ?

les substances apparaissent dans la liste et sont sélectionnables sur les écrans : 

- formulaire d'étapes : 
  - [ ] demande d'octroi
  - [ ] modification de la demande d'octroi
  - [ ] demande de mutation

**Comment by MichaelBitard** [comment]
hésite pas à donner plus d'information sur les tickets, là c'est un peu spartiate.

C'est pour quel cas d'usage ?
Une personne veut faire une concession en stockage souterrain et veut rajouter ces deux substances là ?
