### ISSUE TITLE
Lien accessibilité cassé

### ISSUE THREAD

**Issue by MurielNouguier** [MTES-MCT/camino#587]
## Le problème

Le lien pour la doc d'accessibilité ne fonctionne plus en bas de page : renvoie sur 'https://camino.gitbook.io/guide-dutilisation/a-propos/accessibilite', au lieu de 'https://app.gitbook.com/o/Tl4NriwICf576B9r9xrj/s/BcvrV4rZYKqpbHKGap1w/a-propos/accessibilite'

**Comment by MurielNouguier** [comment]
J'ai ce message sur ce lien:
Échec de la connexion sécurisée

Une erreur est survenue pendant une connexion à camino.gitbook.io. PR_CONNECT_RESET_ERROR

    La page que vous essayez de consulter ne peut pas être affichée car l’authenticité des données reçues ne peut être vérifiée.
    Veuillez contacter les propriétaires du site web pour les informer de ce problème.
    
    C'est peut être mon VPN, je vais voir sans

**Comment by MurielNouguier** [comment]
Argh, c'est mon VPN, désolée pour cette fausse issue....

**Comment by MichaelBitard** [comment]
Pas de souci :D
