### ISSUE TITLE
Terminer l'accessibilité de Camino pour contre-audit

### ISSUE THREAD

**Issue by MichaelBitard** [MTES-MCT/camino#609]
Deux objectifs : 

- Créer des taches quand c'est possible
- Lister les questions pour faire un point avec les personnes qui ont rédigé le rapport

[Rapport Camino Audit RGAA 4.1.pdf](https://github.com/MTES-MCT/camino/files/11831718/Rapport.Camino.Audit.RGAA.4.1.pdf)

**Comment by pohayscamino** [comment]
Filtres
Page à propos
Formulaires
