### ISSUE TITLE
bug(plugin_qgis) : Le plugin qgis ne fonctionne plus

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#642]
J'ai Yoan qui m'écrit : Mon plugin Qgis de Camino ne fonctionne plus. Aucun titre minier n'apparait. Je l'ai réinstallé et généré un nouveau jeton Qgis mais sans succès.

**Comment by MichaelBitard** [comment]
Je viens de trouver l'origine du problème.

Maintenant côté API on contrôle mieux les données qui arrivent chez nous, et il existe plusieurs standards d'URLs pour spécifier des tableaux.

Par exemple pour filtrer par domaine on reçoit `domainesIds=m`. Sauf que là on ne peut pas savoir que c'est un tableau.
On s'attend plutôt à quelque chose comme  `domainesIds[]=m` qui indique que c'est bien un tableau d'éléments, même si il n'y en a qu'un seul.

Deux solutions : 
-1 On supporte les non-tableaux de notre côté
-2 On fait évoluer le plugin QGIS pour qu'il envoie les bonnes infos.

J'ai commencé à travailler sur la solution 2, mais je me suis rendu compte d'un GROS souci soit du plugin, soit de qgis.

À chaque fois que je fais une réquête dans le plugin, c'est **9** requêtes qui partent à notre serveur, pas étonnant que ça soit lent...

**Comment by MichaelBitard** [comment]
En ayant fait la requête directement depuis QGIS, sans passer par le plugin, on voit quand même **8** requêtes qui partent, donc ce n'est pas le plugin le problème, mais bien dans QGIS (version 3.28.10)

**Comment by MichaelBitard** [comment]
@pohayscamino On a trouvé une solution, on va essayer de la livrer en prod en début de semaine prochaine, tu réponds à Yoann ou je le fais ?

**Comment by pohayscamino** [comment]
yes je vais le prévenir que c'est bon dès que j'ai ton go la semaine prochaine et lui demander de me confirmer.

**Comment by pohayscamino** [comment]
J'ai testé avec les cases suivantes



![Image](https://github.com/MTES-MCT/camino/assets/144020267/5195a4ec-63ad-4b4b-83ef-545a0d70e9dc)

**Comment by MichaelBitard** [comment]
Pour ceux qui veulent tester sur d'autres URL que la prod, dans QGIS --> Settings --> Options --> Advanced --> Camino --> Generale, changer les valeurs pour les 3 URL.

prod -> api.camino.beta.gouv.fr
preprod -> api.preprod.beta.gouv.fr
dev -> api.dev.beta.gouv.fr

Garder le reste des URLs sinon plus rien ne fonctionne.

![2023-09-18_16-44-29_grim](https://github.com/MTES-MCT/camino/assets/414642/319ec786-cf74-4384-a2ae-eb859d7a1b1b)

**Comment by pohayscamino** [comment]
J'ai fait la manip



![Image](https://github.com/MTES-MCT/camino/assets/144020267/0d7cb815-f736-47f9-9a7d-76c3b1756dbd)



J'ai ce message d'erreur



![Image](https://github.com/MTES-MCT/camino/assets/144020267/56a88ace-73dc-42f7-abb4-770ae2614979)

**Comment by MichaelBitard** [comment]
Tu as sélectionné quoi pour arriver à cette erreur ?

**Comment by pohayscamino** [comment]
ok ça fonctionne bien
