### ISSUE TITLE
bug(documents) : je télécharge l'ensemble des pièces de l'étape de demande en une seule archive

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#647]
Demande de Yoan  : télécharger l'ensemble de la demande d'ARM en un seul fichier zip. 

Je pense que pour l'ensemble des titres, ça pourrait être pas mal d'avoir un bouton au niveau des étapes "Documents liés à l'étape demande" et "Documents d'entreprise" qui permet de telecharger l'ensemble des fichiers de l'étape dans une archive. 

Pour illustrer ma proposition : 

![Image](https://user-images.githubusercontent.com/144020267/268323945-12f54a60-cdbe-4837-b3a2-38de07e19e56.png)

**Comment by MichaelBitard** [comment]
@pohayscamino pour nous ça fonctionne, il faut savoir sur quelle démarche ça plante

**Comment by pohayscamino** [comment]
voici les deux titres qui causent problème : 
- Degrad Bois Blanc
- Pain de sucre

le message d'erreur est : 

![Image](https://github.com/MTES-MCT/camino/assets/144020267/26505b95-ba03-4639-8418-fb63542f162b)

**Comment by pohayscamino** [comment]
J'ai testé chez moi et le téléchargement ne se lance pas

**Comment by MichaelBitard** [comment]
Problème identifié, il s'agit du téléchargement des fichiers d'entreprise qui ne fonctionne plus dans ce cas là.

**Comment by pohayscamino** [comment]
J'ai testé pour Pain de sucre et c'est bon. L'autre il n'existe pas en preprod
