### ISSUE TITLE
feat(MonServiceSécurisé): passe l'audit de sécurité

### ISSUE THREAD

**Issue by MichaelBitard** [MTES-MCT/camino#648]
On a commencé à créer un compte sur https://www.monservicesecurise.ssi.gouv.fr

On a crée un service pour auditer Camino --> https://www.monservicesecurise.ssi.gouv.fr/service/1a255117-0ec3-4a11-9cd6-ecb1cf0f7492/descriptionService

Il y'a plein de questions auquel il faudrait qu'on se pose pour y répondre, avant de pouvoir déclencher un audit

**Comment by MichaelBitard** [comment]
@pohayscamino si tu te crées un compte sur https://www.monservicesecurise.ssi.gouv.fr/ on peut te rajouter au service Camino pour que tu y aies accès également

**Comment by pohayscamino** [comment]
Y a une organisation CAMINO(92) qui existe. C'est celle-la que je dois choisir?

**Comment by pohayscamino** [comment]
non
