### ISSUE TITLE
fix(activités): impossible d’accéder à la page Activités pour Tirinzonie Flavie

### ISSUE THREAD

**Issue by vmaubert** [MTES-MCT/camino#650]
Quand elle essaye d’accéder à la page : Erreur: vous n'avez pas le droit d'accéder à ce contenu

**Comment by vmaubert** [comment]
@pohayscamino seules les administrations de ces types `ADMINISTRATION_TYPE_IDS.MINISTERE, ADMINISTRATION_TYPE_IDS.DEAL, ADMINISTRATION_TYPE_IDS.DREAL` peuvent accéder aux activités. 

Est-ce que j’ajoute une exception pour la préfecture de Guyane ?

**Comment by pohayscamino** [comment]
oui. J'ai prévenu Jean-Raymond
