### ISSUE TITLE
bug(Plugin_qgis) : Le filtre substance ne fonctionne pas

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#653]
J'ai utilisé le plugin Qgis et indiqué la substance or mais la couche qui est sortie contient toutes les substances

**Comment by MichaelBitard** [comment]
Deux problèmes : C'est lié au plugin QGIS (PR en cours de leur côté https://github.com/MTES-MCT/camino-flux-QGIS/pull/13) et on s'attend à des substances légales qui ont un Id (pour l'or, c'est 'auru')

Idée : avoir une liste dans le plugin QGis et pas un champ libre
