### ISSUE TITLE
feat(cartes) : Je voudrais que la carte soit mise en page pour une impression pdf

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#656]
@POH doit proposer un header et un footer

**Comment by pohayscamino** [comment]
voici ce que je vous propose. Je ne sais pas si Sarah tu veux repasser dessus. L'idée est de mettre des composants du site les uns sous les autres je pense. On va peut être pas pouvoir trop designer.



![Image](https://github.com/MTES-MCT/camino/assets/144020267/88136433-2cf1-4311-8fab-f05ba09e305b)

**Comment by vmaubert** [comment]
@pohayscamino 
En mode rapide, c’est pas possible. 
Bilan : 
 - C’est facile de cacher/afficher ce qu’on souhaite pour imprimer
 - La position de la la carte n’est pas conservée
 - Il manque pas mal d’éléments sur la carte, par exemple les clusters
 - On a essayé différents plugins, sans succès
 - Une solution intéressante à creuser serait d’utiliser un service dans l’API pour générer une image représentant la carte. On a trouvé cette lib => https://www.npmjs.com/package/staticmaps . Malheureusement ce n’est pas possible à faire en mode « rapide ».
