### ISSUE TITLE
feat(cartes) : J'aimerais que la carte soit préfiltrée

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#657]
## Checklist

* [ ] En tant qu'utilisateur de n'importe quelle administration (admin/éditeur/lecteur), quand je clique sur "Démarches" puis que je clique sur "Titres et autorisations" je vois les filtres prédéfinis appliqué
* [x] En tant que tout autre utilisateur, ce comportement n'est pas présent

On part sur : 
- grand public et entreprises on ne touche rien. 
- adminitsration @POH spécifie les pré-filtres

**Comment by pohayscamino** [comment]
voici les filtres



![Image](https://github.com/MTES-MCT/camino/assets/144020267/8030ac11-7b79-4924-9eed-e6b79924abb9)



![Image](https://github.com/MTES-MCT/camino/assets/144020267/1ee5a887-0b32-4a73-b24f-f4c5bf3e2259)




![Image](https://github.com/MTES-MCT/camino/assets/144020267/c4ac6604-90b0-4117-b3ea-93b0422b7bff)

**Comment by pohayscamino** [comment]
je me suis mis sur le profil de Cécile Caron et il n'y a pas de filtre pré-selectionné. nI SUR MON PROFIL aDMIN

**Comment by MichaelBitard** [comment]
Il est fermé automatiquement quand on a livré ça en dev, j'essaie de voir comment arrêter ce comportement.
Mais tu peux voir qu'il n'a pas été livré encore, il est toujours dans la colonne "En dev" chez nous. Et tu ne l'as pas recetté encore
