### ISSUE TITLE
feat(cartes) : Mettre le nombre de titres agglomérés dans les points de la carte

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#658]
@Sarah propose un design

**Comment by SarahOmayra** [comment]
Je me disais qu'au lieu d'ajouter une bulle à la bulle, est-ce qu'on ne pourrait pas se servir des codes couleurs et indiquer la quantité comme suit :



![Image](https://github.com/MTES-MCT/camino/assets/22655315/8015d7e1-05cc-4ec9-ba78-985521683a63)

**Comment by pohayscamino** [comment]
Dur à dire. Je pense que malheureusement on ne le saura qu'en leur montrant une version en preprod comme ça. Alors partons là-dessus et prenons le risque.

@Vincent et @Michael faudra qu'on travaille les tailles. Pour moi les points sont déjà un peu gros et faut pas qu'il y ait une grande différence de taille entre quand il y a un 1 et un 30 vu qu'il y a deja un chiffre écrit dessus

**Comment by MichaelBitard** [comment]
Ça donne ça... 

![2023-09-25_17-01-28_grim](https://github.com/MTES-MCT/camino/assets/414642/bfe5d8fb-40c3-496e-84be-adf41f460fc2)
![2023-09-25_17-01-21_grim](https://github.com/MTES-MCT/camino/assets/414642/ce06ab3f-75d7-4901-a748-92b022b235ed)

**Comment by pohayscamino** [comment]
J'aime bien l'idée de la seconde carte. Est-ce que tu pourrais faire des ronds plus petits et une police plus petite (même taille que le mot "Barcelone")? Et les ronds 10+ plus grands que les autres?

**Comment by MichaelBitard** [comment]
![2023-09-26_09-18-52_grim](https://github.com/MTES-MCT/camino/assets/414642/89e9c476-8ff3-4dea-8048-209b2b0cd58c)

**Comment by MichaelBitard** [comment]
On part là dessus pour le moment, ça peut être intéressant de voir du côté de ce que fait leaflet : 
![2023-09-26_09-28-42_grim](https://github.com/MTES-MCT/camino/assets/414642/aba73195-efa8-4b73-a19e-1fb6200de9c7)

Ils changent vraiment de type de marker quand ils ne sont plus groupés, et ça fait une plus jolie distinction visuelle sur la carte, ANHA.

@pohayscamino @SarahOmayra si vous avez des idées

**Comment by MichaelBitard** [comment]
Les marqueurs quand on est zoomé, tout comme afficher le '1' ou le domaine du titre, c'est la même chose, il s'agit de l'affichage du centre d'un titre, et il faut réfléchir à comment le différencier des groupes de titres (où le nombre est affiché).

Perso je trouve que afficher '1' quand il y'a un seul titre au lieu de son domaine ça va être hyper confusant quand on va zoomer à fond et qu'il y'aura plus que des 1 partout. Ça ne semble pas être une bonne solution AMHA, à voir ce qu'en pense Sarah. Peut être qu'au lieu d'avoir un rond on pourrait avoir le rond avec le pointu en dessous, mais de la même couleur que le domaine et avec le nom du domaine dedans, je ne sais pas

**Comment by pohayscamino** [comment]
J'ai fait le test avec quelques agents. Le mélange de lettres et de chiffres est assez confusant pour eux. Peut être qu'on devrait mettre que des chiffres (donc des 1) jusqu'au zoom 10. A partir de ce zoom, sauf erreur de ma part il n'y a plus d'agglomération donc on met les lettres à partir de ce niveau de zoom.

Pour le fait que le rond ressemble plus à un marqueur à des zoom important je suis pas mal partant.

**Comment by MichaelBitard** [comment]
C'était pas clair pardon, mais techniquement ce n'est pas possible (en tout cas pas simplement, sans réecrire une grosse partie du composant de carte) pour nous d'afficher 1 ou le domaine pour un seul titre suivant le niveau de zoom. C'est exactement le même composant qui est masqué/affiché quand il est groupé avec d'autres.

@vmaubert tu peux me contredire là dessus ;)

**Comment by vmaubert** [comment]
> C'était pas clair pardon, mais techniquement ce n'est pas possible (en tout cas pas simplement, sans réecrire une grosse partie du composant de carte) pour nous d'afficher 1 ou le domaine pour un seul titre suivant le niveau de zoom. C'est exactement le même composant qui est masqué/affiché quand il est groupé avec d'autres.


@MichaelBitard Avec deux layers différents ça doit être faisable facilement. 
- Un layer avec que des chiffres si zoom < 10
- Un layer avec que des lettres (pas de clusters) si zoom >= 10

**Comment by MichaelBitard** [comment]
Oui j'y pensais, mais ça veut dire désactiver le layerclustergroup à la main, et dupliquer tous les marqueurs de la carte.
Je pense que le temps qu'on va y passer VS "Désigner/implémenter un marqueur solo différent du groupé" ne vaut pas le temps qu'on va y passer (sans compter que les perfs vont se ressentir à mon avis

**Comment by SarahOmayra** [comment]
![Image](https://github.com/MTES-MCT/camino/assets/22655315/f6ec33cf-7542-4faf-9de8-1fdad122998d)

lien figma : https://www.figma.com/file/bfhCJYB07yLm9haLZtSRqG/Camino-librairie?type=design&node-id=0%3A1&mode=design&t=DwnQFtdYFJdenO6z-1

**Comment by pohayscamino** [comment]
ça me va bien
