### ISSUE TITLE
feat(instruction) : J'aimerais pouvoir voir facilement les dossiers de mon administration en cours d'instruction

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#659]
@POH regarde si tdb des administrations locales pas déjà ok
A minima faire pour les administrations centrales sur même principe que les locales

**Comment by pohayscamino** [comment]
Je suis allé sur le compte d'un agent DREAL - Hauts-de-France . Je ne vois aucun titre dans son tableau de bord.

**Comment by pohayscamino** [comment]
Je suis allé sur le compte d'un agent DGTM : le tbd répond au besoin

**Comment by pohayscamino** [comment]
Je propose de faire le même tableau de bord que la DGTM pour toutes les DREAL (chacun sur son périmètre).
Pour la DGALN/DGEC sur la périmètre France entière

Je leur montrerai en preprod.

Pour les 3 graphiques :

**Comment by pohayscamino** [comment]
- le premier graph n'est pas à garder pour les DREAL (mais à garder pour l'administration centrale)
- le second graph doit avoir "ARM déposées" et "ARM octroyées", en plus pour la guyane
 et avoir "Concession déposées" et "Concessions octroyées", "PER déposés" et "PER octroyés" à la place pour les DREAL
et l'ensemble des 8 pour les administrations centrales
- le troisième graph je ne le comprends pas trop

**Comment by MichaelBitard** [comment]
Proposition : Pas de graphes pour le moment sur les autres dashboard, on verra à l'usage ce qu'ils veulent. ça te va @pohayscamino  ?

**Comment by pohayscamino** [comment]
ok oui
