### ISSUE TITLE
feat(stats) : J'aimerais que la page statistique soit plus identifiable

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#661]
## Checklist

* [x] Vérifier que les menus s'affichent toujours correctement

On peut tricher en allant voir directement le storybook de preprod avec la simulation des différents roles d'utilisateurs --> https://storybook.preprod.camino.beta.gouv.fr/?path=/story/components-page-header--super

**Comment by pohayscamino** [comment]
Supprimer le lien en bas de page et remettre un onglet statistiques

**Comment by pohayscamino** [comment]
L'onglet doit se trouver entre "Activité" et "Annuaire"

**Comment by pohayscamino** [comment]
ok pour le compte opérateur et admin. Par contre ça n'apparait pas pour l'absence de comptes

**Comment by MichaelBitard** [comment]
Tu veux dire que tu n'as pas ça ?
Parce que le screenshot vient de la preprod à l'instant :)

![2023-09-26_14-00-34_grim](https://github.com/MTES-MCT/camino/assets/414642/f8b5d061-2b94-4bcc-90c7-7b468d4b8b20)

**Comment by pohayscamino** [comment]
C'est tout bon.

Il me manquait un petit F5 :)
