### ISSUE TITLE
feat(cartes) : J'aimerais pouvoir vérifier sur la carte que le périmètre d'un titre n'est pas sur une zone protégée

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#665]

**Comment by pohayscamino** [comment]
Est-ce que Camino peut faire un appel à l'API de geoportail et faire des avertissement si le titre touche toute zone des couches de l'onglet "Espaces protégés" du geoportail? Pas besoin de montrer les couches geoportail. Juste des avertissements.

Un avertissement lors du dépôt de la demande. Un avertissement lors de la notification DREAL suite à Accusé de réception;



![Image](https://github.com/MTES-MCT/camino/assets/144020267/31460e9b-a131-4038-87d4-e65428e93c79)

**Comment by vmaubert** [comment]
@pohayscamino Malheureusement on ne peut pas utiliser Géoportail car dans la majorité c’est juste des images. Donc on ne peut pas interpréter les images. MAIS on va regarder si on peut directement récupérer la donnée sous format Géojson pour faire nos calculs d’intersection. Est-ce que tu as une priorité dans les différents fonds de carte ?
Pour info c’est ce qu’on a fait pour le SDOM et les forêts.

**Comment by pohayscamino** [comment]
ah ok. plus compliqué que je le pensais s'il faut essayer de trouver des jeux de données. 

Alors voici l'ordre de priorité : 
- arrêt de protection du biotope
- sites natura 2000
- parcs nationaux
- réserves naturelles nationales
- parcs régionaux
- réserves naturelles régionales
- parcs naturels marins
- conservatoire du littoral
- sites classés
- sites inscrits

**Comment by pohayscamino** [comment]
Warning comme pour zones du SDOM pour celui qui dépose la demande et visible sur l'étape de demande
Warning recevabilité de la demande
