### ISSUE TITLE
feat(cartes) : J'aimerais des filtres plus simples à utiliser

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#670]
Besoin de design

**Comment by pohayscamino** [comment]
vérifier quels filtres sont les plus utilisés
Est-ce que plutôt Carto que liste?

**Comment by SarahOmayra** [comment]
Proposition : 


![Image](https://github.com/MTES-MCT/camino/assets/22655315/4ef3991b-8a22-4ab4-bde2-464034ab8e2e)

**Comment by pohayscamino** [comment]
ça me va bien mais il faudra que quand on réduit le filtre on puisse voir en dessous ce qui a été coché (comme actuellement)

**Comment by pohayscamino** [comment]
ca qu'on s'était dit c'est qu'il faudrait surement faire un mix avec le ticket #671 car la mise en page va jouer

**Comment by SarahOmayra** [comment]
il reste à statuer sur les filtres d'étapes : on garde ou pas, on garde tout ou juste un filtre sur l'étape et pas sur les dates de débuts, de fin, de statuts :

https://www.figma.com/file/qNgko8jWRp4UQMPHF5a2i5/Camino?type=design&node-id=1481%3A41085&mode=design&t=H6SqgGUoLbB9W466-1

**Comment by pohayscamino** [comment]
Quand on clique sur un filtre il faut que ça mette à jour la carte sans cliquer sur valider

**Comment by SarahOmayra** [comment]
Composants filtres: 
https://www.figma.com/file/bfhCJYB07yLm9haLZtSRqG/Camino-librairie?type=design&node-id=493%3A7123&mode=design&t=qEN2yrBa7WfLbpfX-1
Pages démarches et titres : 
https://www.figma.com/file/qNgko8jWRp4UQMPHF5a2i5/Camino?type=design&node-id=1240%3A19977&mode=design&t=VcWQ4XWkL2lr6wJy-1

**Comment by pohayscamino** [comment]
trois petits commentaires mais sinon ça me va bien. Très beau travail. c'est top comme ça merci!!!!

**Comment by pohayscamino** [comment]
Par contre faut aussi faire les pages travaux et activités. Même principe

**Comment by pohayscamino** [comment]
@sarah montre à quelques utilisateurs et moi à 2 collègues

**Comment by pohayscamino** [comment]
L'ordre des filtres : 

Noms
Substances
Domaines
Types de titre
Statuts de titre
Entreprises
Types de démarche
Statuts de démarche

**Derrière le bouton "Autres filtres"**
Références
Façades Maritimes
Communes
Départements
Régions
Types d'étapes incluses
Types d'étapes exclues
