### ISSUE TITLE
feat(homologation) : Redesign page démarche

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#686]

**Comment by pohayscamino** [comment]
https://www.figma.com/file/qNgko8jWRp4UQMPHF5a2i5/Camino?type=design&node-id=1062-120830&mode=design&t=M4cdTivoxvaEgg5B-0

**Comment by pohayscamino** [comment]
Nom des points pas de raison de les garder?

**Comment by pohayscamino** [comment]
@SarahOmayra j'ai ajouté des commentaires dans le figma car il faudrait indiquer quelque-part l'étape dont sont issus les infos du résumé et de la carte.

Sauf si tu as une meilleur idée, je propose un truc un direct du style à côté du titre "Résumé" mettre "Résumé (informations provenant de l'étape de XXX).

**Comment by SarahPelt** [comment]
pour améliorer la visibilité des démarches : font-size du titre du tableau : 1rem
effets "overlap" sur chaque card étape
ajouter un bottom-padding d'au moins 24px pour le container (je trouve que ce n'est pas assez espacé entre le main et le footer

**Comment by SarahPelt** [comment]
Pour la frise : https://www.figma.com/file/qNgko8jWRp4UQMPHF5a2i5/Camino?type=design&node-id=1675%3A65992&mode=design&t=ztEsJVD8eBueDbI5-1
