### ISSUE TITLE
feat(homologation) : Redesign de la page titre (Accessibilité)

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#687]
## Checklist

* [x] Un peu tout tester sur la page titre
* [x] Un titre avec des doublons
* [x] Un titre avec des activités non déposées (à tester en super, admin et entreprise)
* [x] Un titre sans démarche
* [x] Malmeix
* [x] Créer une étape
* [x] Tester un titre avec un déplacement de périmètre
* [x] Créer une démarche
* [x] Créer un titre
* [x] Supprimer une démarche/titre/étape
* [x] Modifier le titulaire d'un titre dans une démarche de mutation

**Comment by pohayscamino** [comment]
@SarahOmayra j'ai ajouté des commentaires dans le figma car il faudrait indiquer quelque-part l'étape dont sont issus les infos du résumé et de la carte.

Sauf si tu as une meilleur idée, je propose un truc un direct du style à côté du titre "Résumé" mettre "Résumé (informations provenant de l'étape de XXX de la démarche XXX).

**Comment by SarahPelt** [comment]
Pour la configuration du tableau :

**Comment by SarahPelt** [comment]
J'aurais besoin de toutes les infos que l'on peut mettre dans les colonnes et que l'on fixe un max de colonnes.
Quelles sont celles que l'on met d'office ?

**Comment by pohayscamino** [comment]
Voilà. En rouge les colonnes par défaut


[Colonnes tableaux.xlsx](https://github.com/MTES-MCT/camino/files/13451589/Colonnes.tableaux.xlsx)

**Comment by pohayscamino** [comment]
J'avais un titre (Chassiron D) qui avait un octroi puis une prolongation. J'ai supprimé la démarche d'octroi. Ça a créé un bug. Ce serait peut être mieux qu'on interdise de supprimer une démarche tant que les démarches qui suivent n'ont pas été supprimées (comme pour les étapes d'une démarche).



![Image](https://github.com/MTES-MCT/camino/assets/144020267/02223133-4ed0-44e2-9059-b358eaeef96a)

**Comment by pohayscamino** [comment]
Sur le titre Antully : https://preprod.camino.beta.gouv.fr/titres/m-cx-antully-1973?demarcheSlug=m-cx-antully-1973-mut01

J'ai modifié l'opérateur de la mutation pour l'étape JORF. Le résumé ne donne pas le bon. Il a gardé celui de la décision de l'administration et n'a pas pris en compte celui de l'étape de publication JORF



![Image](https://github.com/MTES-MCT/camino/assets/144020267/29b5b2c6-d4f3-427f-bc24-53fd424c6552)

**Comment by pohayscamino** [comment]
Sur le titre suivant : https://preprod.camino.beta.gouv.fr/titres/f-cx-glageon-couplevoie-1825?demarcheSlug=f-cx-glageon-couplevoie-1825-exp01

J'ai voulu déposer une extension de périmètre en déposant un multipolygone mais un seul des deux polygone a été uploadé

**Comment by vmaubert** [comment]
> J'avais un titre (Chassiron D) qui avait un octroi puis une prolongation. J'ai supprimé la démarche d'octroi. Ça a créé un bug. Ce serait peut être mieux qu'on interdise de supprimer une démarche tant que les démarches qui suivent n'ont pas été supprimées (comme pour les étapes d'une démarche).

J’ai pas de solution magique. Je ne pense pas que ça soit une bonne idée de mettre ce mécanisme. J’ai peur de bloquer la correction des vieux titres.



> Sur le titre Antully : https://preprod.camino.beta.gouv.fr/titres/m-cx-antully-1973?demarcheSlug=m-cx-antully-1973-mut01
> 
> J'ai modifié l'opérateur de la mutation pour l'étape JORF. Le résumé ne donne pas le bon. Il a gardé celui de la décision de l'administration et n'a pas pris en compte celui de l'étape de publication JORF. Mais ça ne sera plus un sujet quand on aura fusionné les deux étapes.

Oh non ça c’est un gros bug, je viens de le corriger en local. Faudra tester à la prochaine recette.



> Sur le titre suivant : https://preprod.camino.beta.gouv.fr/titres/f-cx-glageon-couplevoie-1825?demarcheSlug=f-cx-glageon-couplevoie-1825-exp01
> 
> J'ai voulu déposer une extension de périmètre en déposant un multipolygone mais un seul des deux polygone a été uploadé

Pour le coup, on a pas touché à ça (j’espère), peux-tu nous fournir le fichier en question stp.

**Comment by pohayscamino** [comment]
Pour chassiron D on ne pourrait pas juste alors estimer que toutes les démarches ont été supprimées et qu'on revient à un état équivalent à demander un titre sans avoir rien complété? 

Quand on demande un titre vide une démarche d'octroi et une étape de demande (en construction) sont automatiquement crées comme là : https://preprod.camino.beta.gouv.fr/titres/m-pr-test-per-2024?demarcheSlug=m-pr-test-per-2024-oct01

**Comment by pohayscamino** [comment]
Pour le mobile : 

- le bouton s'abonner sort de l'écran

![Image](https://github.com/MTES-MCT/camino/assets/144020267/e06299ba-eaf0-4138-943f-39c356a4521a)


- les tableaux dans les étapes sortent de l'écran


![Image](https://github.com/MTES-MCT/camino/assets/144020267/774bda68-389d-458f-9c2b-34b67ab626a7)


- la frise devient illisible car compressée alors qu'elle devrait être scrollable horizontalement


![Image](https://github.com/MTES-MCT/camino/assets/144020267/3eaabd46-db74-4ab2-855e-cb5a0636f26e)
