### ISSUE TITLE
feat(homologation) : Diviser le statut "modification en instance" en deux nouveaux statuts

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#689]
## Checklist

* [ ] Vérifier quelques titres qui sont en survie provisoire
* [ ] Vérifier quelques titres qui sent en cours de modification
* [ ] Mettre à jour la documentation sur gitbook concernant les statuts des titres

Les nouveaux statuts proposés sont : "valide - survie provisoire" et "valide - en cours de modification"

@Sarah voir quelle couleur mettre (échelle de vert pour ce qui est valide serait bien je pense)

**Comment by SarahOmayra** [comment]
3 niveaux de vert

**Comment by vmaubert** [comment]
@pohayscamino voici la description qu’on a actuellement pour la « Modification en instance ». 

`Titres et autorisations qui font l’objet d’une démarche de modification de leurs propriétés fondamentales (durée, surface, titulaire, amodiataire, substances). Le domaine minier demeure fermé pour les substances et usages visés par la demande en cours, jusqu'à ce qu'il soit statué sur la demande de modification.
Tant que l’administration ne s’est pas prononcée par décision expresse, le pétitionnaire bénéficie du droit de poursuivre ses travaux dans les limites du périmètre et des substances visées par la nouvelle demande même après une décision implicite de rejet. Au delà de sa date de validité, le titre est dit en "survie provisoire".`

Peux-tu nous fournir les 2 nouvelles descriptions stp ?

**Comment by SarahOmayra** [comment]
![Image](https://github.com/MTES-MCT/camino/assets/22655315/9f5d990d-026c-4148-bb2e-913f63fae1c1)

figma : https://www.figma.com/file/bfhCJYB07yLm9haLZtSRqG/Camino-librairie?type=design&node-id=457%3A19101&mode=design&t=ZXAVYH87UzswWgiH-1

classes de vert background : 
valide  : --light-background-contrast-success, #B8FEC9
valide-survie provisoire : --light-accent-green-bourgeon-950, #C9FCAC
valide-en cours de modification : --light-accent-green-bourgeon-975, #E6FEDA

classe vert écriture : --light-text-default-success, #18753C

**Comment by vmaubert** [comment]
@SarahOmayra 👌 
C’est normal d’avoir une icone que sur le 1er statut ?

**Comment by pohayscamino** [comment]
non pas d’icône. Mais à garder en tête pour le ticket de redesign des filtres ;)
