### ISSUE TITLE
feat(url): lors de l'étape d'ouverture de la participation au public, on veut pouvoir saisir une URL vers la participation du public

### ISSUE THREAD

**Issue by MichaelBitard** [MTES-MCT/camino#702]
# Checklist

* [ ] Aller sur une étape d'ouverture de la participation du public, et voir que l'on peut saisir une URL dans le détail de l'étape

# Pourquoi
À l'heure actuelle on utilise les documents pour stocker cette information, alors que ça devrait être lié à l'étape

Étape précédente à:
 * #675

étape qui pose problème : https://camino.beta.gouv.fr/etapes/bb49d4b82c4bee721fb1f657

**Comment by pohayscamino** [comment]
lié au ticket #576

**Comment by pohayscamino** [comment]
Il y a aussi l'étape d'ouverture d'une enquête publique qui devrait être concernée par la même chose.



![Image](https://github.com/MTES-MCT/camino/assets/144020267/d9238c0f-0457-47c5-88b4-ea489cafd639)
