### ISSUE TITLE
feat(UX) : permettre de filtrer par département dans l'annuaire des entreprises

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#704]

**Comment by MichaelBitard** [comment]
Techniquement, on a des fois son code postal, des fois sa commune, mais pas sûr.

Ça ne sera pas un résultat "parfait", ça peut prêter à confusion. On fait quand même ?

**Comment by pohayscamino** [comment]
j'ai mal spécifié désolé.

C'était une demande d'Emilien Dru en date du 6 septembre. Mais je ne vois pas l'utilité de pouvoir filtrer par département les sièges juridiques des entreprises. Je pense qu'en fait ce qui les intéresse c'est d'avoir la liste des entreprises qui ont des titres en Guyane. 

Donc un filtre "entreprises ayant des titres dans le département de " .

Est-ce que tu penses que c'est galère techniquement?
J'ai questionné la DGTM pour mieux identifier leur besoin

**Comment by vmaubert** [comment]
@pohayscamino Ok ça paraît logique et réalisable relativement facilement.
