### ISSUE TITLE
fix(téléchargement): l’application plante si on essaye de télécharger un zip trop gros

### ISSUE THREAD

**Issue by vmaubert** [MTES-MCT/camino#718]
Bug remonté par email par un utilisateur.

Si on essaye de télécharger le zip de l’étape https://camino.beta.gouv.fr/etapes/m-pr-brevenne-2023-oct01-mfr01/ l’application plante.

**Comment by pohayscamino** [comment]
je peux télécharger le fichier? Je ne vais pas faire redémarrer la machine?

**Comment by vmaubert** [comment]
@pohayscamino Oui tu peux
