### ISSUE TITLE
feat(publication) : supprimer les URL et permettre d'ajouter la décision automatiquement avec le numéro de JORF

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#728]

**Comment by MichaelBitard** [comment]
la #744 travaille sur une partie de cette tache.
On a enlevé URL, URI, NOR, JORF des documents et on a rajouté des sections pour que les personnes puissent saisir le JORF et le NOR lors des étapes : 
- publication de décision au JORF
- décision de l'administration
- avis de mise en concurrence au JORF
- publication de décision administrative au JORF
- décision administrative
- publication de l'avis de décision implicite
- abrogation de la décision

De plus, nous avons rajouter un champ 'url' à l'étape "ouverture de la participation du public"
