### ISSUE TITLE
feat(QGIS) : ajouter les informations pour utiliser l'API directement quand on clique sur le jeton QGIS

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#745]
Quand on clique sur le bouton "générer un jeton QGIS", on indique le nom d'utilisateur et l'URL pour QGIS

**Comment by MichaelBitard** [comment]
Il va falloir qu'on retravaille cette page un jour, peut être avecc l'aide de @SarahOmayra dessus parce qu'on a pas vraiment de composant "Card/Accordion" dans le DSFR  pour afficher des informations comme ça.

En tout cas maintenant, quand on clique sur "Générer des identifiants pour QGis", l'URL est directement copiée dans le presse-papier

![2023-10-10_17-29-26_grim](https://github.com/MTES-MCT/camino/assets/414642/162f7c7d-f857-46dd-9c3a-6eb0b51e7b9d)
![2023-10-10_17-26-48_grim](https://github.com/MTES-MCT/camino/assets/414642/ef539281-9679-4aaf-81d7-80ac7b5e3777)

**Comment by pohayscamino** [comment]
Il faut ajouter le nom d'utilisateur car là aussi il faut savoir que c'est l'adresse mail et penser au %40

**Comment by vmaubert** [comment]
@pohayscamino il a tout mis dans l’url, ça devrait marcher directement dans Qgis sans mettre d’authentification

**Comment by pohayscamino** [comment]
ok top tu peux pousser en preprod

**Comment by vmaubert** [comment]
@pohayscamino Je pense qu’on peut grave améliorer ça (sans bloquer cette livraison).
On devrait proposer de générer l’url pour utiliser l’api directement dans QGis.
Ou proposer de générer le token pour utiliser le plugin Camino (en précisant que ce n’est pas la méthode recommandée).

**Comment by MichaelBitard** [comment]
![Image QGIS](https://github.com/MTES-MCT/camino/assets/414642/480e9277-fce0-4719-b291-50eb6a623e5c)
