### ISSUE TITLE
bugg(desistement) : désistement d'une prolongation NEM 4

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#749]

**Comment by pohayscamino** [comment]
Bonne remarque. Dans ce cas là quand on fait un désistement, au lieu d'indiquer le nom de la démarche on indique "survie provisoire" à la place? Là ça remplace "Prolongation 1" par "survie provisoire"

**Comment by pohayscamino** [comment]
si modif en instance rien mettre comme autre démarche
si survie provisoire il faut mettre ce terme et pas la démarche.

frise chronologique serait pas mal.

**Comment by MichaelBitard** [comment]
@pohayscamino on fait du nettoyage de tickets plus valides.

On est d'accord que l'arrivée de la frise change tout et rend cette issue obsolète.
Je la cloture, re-ouvre si c'est pas ok pour toi
