### ISSUE TITLE
feat(url): lors de l'étape d'ouverture d'ouverture de l'enquête publique, on veut pouvoir saisir une URL vers le site de l'enquête publique

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#754]

**Comment by pohayscamino** [comment]
Il y a aussi l'étape d'ouverture d'une enquête publique qui devrait être concernée par la même chose.

Image

**Comment by MichaelBitard** [comment]
C'est bon comme ça ?

![2023-10-25_09-41-59_grim](https://github.com/MTES-MCT/camino/assets/414642/277c8998-db3e-42a9-8edb-92e1a28675cc)

**Comment by pohayscamino** [comment]
très bien
