### ISSUE TITLE
bug(instruction) : indiquer qu'on parle de la procédure et pas de la validation de la démarche

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#757]
Dans l'exemple si dessous on a l'impression que la prolongation a débuté au 02-02-2021, or c'est la demande de prolongation qui a débuté. La prolongation ne débutera quà la notification de la décision au JORF. 

De plus la date est celle de l'octroi mais pas du début de la demande

![Image](https://github.com/MTES-MCT/camino/assets/144020267/2f63344f-7026-4ebc-99df-7301f6b7e064)

**Comment by vmaubert** [comment]
« La prolongation ne débutera qu’à la notification de la décision au JORF. » @pohayscamino tu es certain de ça ?

**Comment by pohayscamino** [comment]
non elle sera rétroactive et commencera à partir de la fin de la validité de l'octroi. Mais ça ne sera vrai qu'à la notification de la décision. Donc on ne peut pas l'indiquer comme on le fait en cours d'instruction. En cours d'instruction c'est l'octroi initial qui voit sa période de validité prolongées par la survie provisoire.

**Comment by pohayscamino** [comment]
même chose que ticket #749
