### ISSUE TITLE
(secu) : mettre en place un 2FA pour les comptes admin

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#761]

**Comment by MichaelBitard** [comment]
Ok pour faire simple, on peut le faire pour les utilisateurs super en s'appuyant sur cette discussion : 
https://github.com/keycloak/keycloak/discussions/13167

Je viens de le faire en dev, j'attends l'arrivée de vincent demain et on le cale en prod.

![2024-03-18_17-00-32_grim](https://github.com/MTES-MCT/camino/assets/414642/034b79d2-a34d-4f03-ae85-f20374055158)

**Comment by MichaelBitard** [comment]
Fait en prod directement dans keycloak
