### ISSUE TITLE
(secu) : demande de reset des MDP des comptes

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#762]

**Comment by pohayscamino** [comment]
Pour respecter les nouveaux critères (keycloak par défaut).

**Comment by MichaelBitard** [comment]
Le plus simple et de forcer tout le monde à re-rentrer son mot de passe.

Après on peut être plus malin et ne forcer que ceux qui sont toujours sous l'ancien algorithme de chiffrement (bcrypt), mais ça veut dire qu'on aura toujours des utilisateurs avec des mots de passe qui ne respectent pas les nouveaux critères.

On n'a pas de moyen de savoir si les mots de passe des utilisateurs respectent les critères qu'on a mis après malheureusement

**Comment by MichaelBitard** [comment]
Ha si, encore plus simple et en accord avec ce qui s'est dit pendant le réunion homologation sécurité, on peut forcer les utilisateurs à changer de mot de passe tous les N jours, c'est facile à mettre en place (2 clics)

C'est peut être la meilleure solution

**Comment by MichaelBitard** [comment]
Fait en prod directement dans keycloak.
On force le changement de mot de passe tous les 365 jours et on interdit de réutiliser les 3 mots de passe précédents
