### ISSUE TITLE
feat(instruction): mettre des noms de fichiers compréhensibles dans les archives exportables

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#763]
J'ai téléchargé un dossier initial complet en .zip et voilà le nom des fichiers qui s'y trouvent. C'est compliqué de retrouver ses petits.

![Image](https://github.com/MTES-MCT/camino/assets/144020267/10265625-580e-45cf-9037-f9f0fe75aae6)

Je propose qu'on mette comem noms de fichiers les descriptions en minuscule avec "_" entre chaque mot.

![Image](https://github.com/MTES-MCT/camino/assets/144020267/2e55e989-01fa-461c-ae42-a065657ad822)

**Comment by MichaelBitard** [comment]
Ça donne ça maintenant, pour les ZIP
![Uploading 2023-12-07_09-19-23_grim.png…]()

**Comment by pohayscamino** [comment]
ça vient d'où la partie "-jid-79d290cc-" dans le premier fichier? Est-ce que c'est vraiment utile de l'indiquer?
Si deux fichier ont le même nom on peut mettre un (1) à la fin du second (comme sur windows)?

**Comment by pohayscamino** [comment]
Le bouton ne fonctionne pas. Y a marqué "problème avec le serveur".

**Comment by vmaubert** [comment]
@pohayscamino Michael n’a pas restauré les fichiers sur la preprod, car elle n’a pas accès aux backups (nouvelle IP) pour le moment.
Je viens de créer une nouvelle demande et on peut télécharger le zip => https://preprod.camino.beta.gouv.fr/titres/c-ar-test-vm-2024?demarcheSlug=c-ar-test-vm-2024-oct01
