### ISSUE TITLE
bug(compte) : mails envoyés lors de la suppression d'un compte

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#776]
## Checklist

* [x] En tant que super, je peux supprimer un utilisateur (il disparait des utilisateurs de camino et de keycloak)
* [x] En tant qu'utilisateur, je peux supprimer mon compte (je me fais automatiquement déconnecter et cet utilisateur n'apparait plus dans keycloak)

Lors de la suppression d'un compte, l'utilisateur doit recevoir un mail lui confirmant la suppression du compte et ne doit plus recevoir les deux mails de "bienvenu" et de "confirmations de la création d'un compte".

**Comment by MichaelBitard** [comment]
Il s'agit d'un beau bug, la suppression ne fonctionne pas

**Comment by pohayscamino** [comment]
Je ne reçois pas le mail me confirmant la suppression du compte

**Comment by pohayscamino** [comment]
Je ne reçois toujours pas le mail de suppression du compte. C'est bien ce que je devais vérifier?

**Comment by MichaelBitard** [comment]
Il n'y a pas de mail de suppression de compte. Tu recevais un mail de **création de compte** parce qu'un bug faisait qu'on te ré-enregistrait sous camino.

Là tu peux vérifier que l'utilisateur n'existe plus dans keycloak, c'est tout

**Comment by pohayscamino** [comment]
alors c'est tout bon
