### ISSUE TITLE
feat(simplification) : refonte de l'étape des avis

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#779]

**Comment by pohayscamino** [comment]
Fichier en cours de validation EARM2

[Simplification des étapes v2.xlsx](https://github.com/MTES-MCT/camino/files/13112703/Simplification.des.etapes.v2.xlsx)

**Comment by pohayscamino** [comment]
simplifications validées

[Simplification des étapes v3.xlsx](https://github.com/MTES-MCT/camino/files/13179656/Simplification.des.etapes.v3.xlsx)

**Comment by SarahPelt** [comment]
Proposition : https://www.figma.com/file/qNgko8jWRp4UQMPHF5a2i5/Camino?type=design&node-id=2093%3A5789&mode=design&t=Jmfe0CdUBP8Nv2E8-1
