### ISSUE TITLE
feat(simplification) : Supprimer les entreprises archivées sans titre ni siren

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#791]

**Comment by MichaelBitard** [comment]
`delete from entreprises where id in (select id from entreprises e where legal_siren is null and e.id not in (select entreprise_id from titres_amodiataires ta) and e.id not in (select entreprise_id from titres_titulaires tt))`

**Comment by MichaelBitard** [comment]
@pohayscamino ça a été fait en production, les entreprises ont été nettoyées, on fait quoi avec mon dernier commentaire ?

**Comment by pohayscamino** [comment]
si pas de titre ni utilisateur associé on supprime. Ce sera invisible pour les utilisateurs. et si besoin on les recréera facilement avec leur siren mais je ne vois pas qui le demandera

**Comment by pohayscamino** [comment]
comment c'est possible que le numéro SIREN ne corresponde à rien alors que le processus oblige un numéro SIREN qui soit retrouvé dans la base siren?

**Comment by MichaelBitard** [comment]
> si pas de titre ni utilisateur associé on supprime. Ce sera invisible pour les utilisateurs. et si besoin on les recréera facilement avec leur siren mais je ne vois pas qui le demandera

C'est fait



> comment c'est possible que le numéro SIREN ne corresponde à rien alors que le processus oblige un numéro SIREN qui soit retrouvé dans la base siren?

C'est vieux, on avait pas la connexion à la base SIREN à l'époque j'imagine

**Comment by pohayscamino** [comment]
ok. On le supprime aussi alors

**Comment by MichaelBitard** [comment]
C'est fait !
