### ISSUE TITLE
feat(fiscalité) : Produire les matrices fiscales pour la DREAL Grand-est

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#810]

**Comment by pohayscamino** [comment]
L'emplacement des modèles de matrices : https://drive.google.com/drive/folders/1uhgRzu5orm6hSR2uq0wgbqbT8MsELpvu

**Comment by vmaubert** [comment]
Plusieurs remarques  : 
- Tu n’as pas une version autre que le pdf ? On gagnerait pas mal de temps avec le format xls ou ods d’origine.
- Peux-tu récupérer une version déjà remplie des années passées ? Ça nous permettrait de mieux comprendre et aussi de nous assurer qu’on met les bonnes infos au bon endroit
- Il y a 3 matrices qui parlent d’hydrocarbure (dont 2 de pétrole), à ma connaissance on a aucune production de pétrole dans Camino

**Comment by pohayscamino** [comment]
Voici les matrices remplies juste avec ce que fait la DREAL. Les matrices remplies nous seront envoyées par la DDFIP.

[matrice_etat-annexe_RDCM_sel_2022.ods](https://github.com/MTES-MCT/camino/files/14791200/matrice_etat-annexe_RDCM_sel_2022.ods)

Par contre il faut récupérer les tonnages extraits par commune.
