### ISSUE TITLE
bug(page démarche) : Erreur quand on crée une nouvelle étape

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#829]
J'ai essayé de créer une nouvelle étape depuis la nouvelle page démarche et j'ai eu ce bug

![Image](https://github.com/MTES-MCT/camino/assets/144020267/e62052c9-e5ed-40e1-a9b8-52420f5f8f97)

**Comment by MichaelBitard** [comment]
Corrigé par la #838
