### ISSUE TITLE
bug(instruction) : Impossible de changer le statut d'une étape

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#831]
Sur le titre suivant : https://preprod.camino.beta.gouv.fr/titres/m-ax-1-2-et-2-2-crique-mac-mahon-2022

J'ai modifié le statut de l'étape "Décision de l'administration". Je l'ai mis à rejetée. Ça marche bien. Maintenant j'essaie de la remettre à "accepté" et là ça ne veut plus.

![Image](https://github.com/MTES-MCT/camino/assets/144020267/e188d3b4-716d-4158-9b49-9f9c0919d9f2)

**Comment by MichaelBitard** [comment]
Corrigé par la #838
