### ISSUE TITLE
bug(suppression d'étapes): Impossible de supprimer une étape

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#832]
En essayant de supprimer des étapes du titre suivant, il ne s'est rien passé. Ça les a juste grisé : https://preprod.camino.beta.gouv.fr/demarches/m-ax-crique-pioupiou-2021-oct01

![Image](https://github.com/MTES-MCT/camino/assets/144020267/86d2a53b-554b-4860-9c99-fd2e4d8f0390)

**Comment by MichaelBitard** [comment]
Corrigé par la #838
