### ISSUE TITLE
feat(frise) : Améliorer la frise chronologique

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#834]
Je pense qu'il faudrait : 
- ajouter une tête de flèche au bout à droite pour bien montrer qu'on est sur une frise chronologique
- peut être faire une frise plus épaisse pour qu'on la voit mieux
- - mieux faire comprendre que c'est une zone/en-tête en dehors de la page de la démarche. Presque que c'est une zone de menu

![Image](https://github.com/MTES-MCT/camino/assets/144020267/90e20a31-30be-4348-97be-d538f6dc528d)

**Comment by pohayscamino** [comment]
Il faut rendre le design plus épuré. Je trouve que la lecture est compliquée car il y a beaucoup d'infos



![Image](https://github.com/MTES-MCT/camino/assets/144020267/55224c42-2bf2-48b9-8fc3-ce1bf9043275)

**Comment by SarahPelt** [comment]
![Image](https://github.com/MTES-MCT/camino/assets/151026049/be8bbdbd-f898-4f8a-b86b-cfe66ac81992)

**Comment by SarahPelt** [comment]
https://www.figma.com/file/qNgko8jWRp4UQMPHF5a2i5/Camino?type=design&node-id=1062%3A120830&mode=design&t=T1sIWrR6jFZJzRLj-1
