### ISSUE TITLE
bug(mobile) : nouvelle page démarche pas accessible en version mobile

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#835]
Dans la version mobile, je ne peux pas appuyer sur le nom d'une démarche pour aller voir la nouvelle page démarche.

**Comment by vmaubert** [comment]
@pohayscamino tu n’étais pas connecté ? Car ça marche bien pour nous.

**Comment by vmaubert** [comment]
@pohayscamino ?

**Comment by pohayscamino** [comment]
ça date ça. C'est ok maintenant
