### ISSUE TITLE
feat(UI) : meilleure séparation entre étapes

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#837]

**Comment by pohayscamino** [comment]
C'est encore un peu juste la séparation entre étapes. Mettre un peu plus de distance entre les étapes



![Image](https://github.com/MTES-MCT/camino/assets/144020267/0bdbdfbf-dca9-407e-9a85-ebb805893d2b)

**Comment by MichaelBitard** [comment]
Corrigé par la #838
