### ISSUE TITLE
bug(carte) : Visibilité des sommets des périmètres

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#872]
Suite à mes tests j'aimerais changer un peu la règle pour voir les point des périmètres. 

En gros il faut que je sois capable de voir des gros périmètres avec leur point comme par exemple : https://preprod.camino.beta.gouv.fr/titres/m-pr-takari-sud-est-2020?demarcheSlug=m-pr-takari-sud-est-2020-oct01

Actuellement à partir d'un certain niveau de zoom les point disparaissent totalement (le calcul point reste coché mais les point n'appariassent plus).

Ce qu'il faudrait c'est que pour ce même niveau de zoom les point disparaissent parque le calque est décoché mais l'utilisateur peut re-cocher le calque et faire apparaitre les points.

**Comment by vmaubert** [comment]
@pohayscamino le problème de ta solution c’est que si la personne passe son temps à zoomer/dézoomer on va lui décocher le calque des points à chaque fois.

On te propose de le laisser cocher par défaut et l’utilisateur pourra les cacher si il le souhaite.

**Comment by pohayscamino** [comment]
ok faisons comme ça
