### ISSUE TITLE
bug(carte) : Visibilité des titres échus

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#873]
Les titres W et G échus ne sont actuellement pas visibles du public. Ils devraient l'être. 

Seuls les titres H échus ne doivent pas être visibles du public

**Comment by vmaubert** [comment]
@pohayscamino Tous les titres suivants passeront public, valides-tu ? 


https://camino.beta.gouv.fr/titres/mkK8CK9X6iT1bMKmksc3gkkl
https://camino.beta.gouv.fr/titres/ZHWE6vIeCqQa6uS0qWBrqyjL
https://camino.beta.gouv.fr/titres/YRijV5QaSGUHayLTqFaNHur0
https://camino.beta.gouv.fr/titres/zmUTSQq79mMNov9jtSuNOSo8
https://camino.beta.gouv.fr/titres/11qSMEb9BA0cub9cpAP7vlxO
https://camino.beta.gouv.fr/titres/7muqu97MmuyT5ohkQ3xKsovh
https://camino.beta.gouv.fr/titres/ZPj3Hcxv6U1vYZ1HtXDaeYIN
https://camino.beta.gouv.fr/titres/MaCYtiSZ3s1ytaRwgLd9tevn
https://camino.beta.gouv.fr/titres/MNddfwwrUZbdaJU85GnVKgmY
https://camino.beta.gouv.fr/titres/LsXP1bEbudUqH2dJozZxMupE
https://camino.beta.gouv.fr/titres/4JcDCfJA8MLrGjYhZtPdgqr9
https://camino.beta.gouv.fr/titres/9I279EDcqKzdQzFiniF3fbh0
https://camino.beta.gouv.fr/titres/4OMbEDD5cijSN5jNPaAFOl43
https://camino.beta.gouv.fr/titres/kEUbWGqriLuXI9BtgO8Zn0eF
https://camino.beta.gouv.fr/titres/YkzVQlG3pplkllkwB9qajDww
https://camino.beta.gouv.fr/titres/UEc46CWDy6E6MFkUScDojIch
https://camino.beta.gouv.fr/titres/qBFYTi9rFCqLbLG5Cy75g1nx
https://camino.beta.gouv.fr/titres/DWm1RAZj2zUfWUBHoQcVldxF
https://camino.beta.gouv.fr/titres/pavDTpDqmtidLY3nic80G0Zp
https://camino.beta.gouv.fr/titres/ndZoh9zpJ9iUUkcrqWPuBpKo
https://camino.beta.gouv.fr/titres/ZN2xqNBJBeydZV3cPmD9iywf
https://camino.beta.gouv.fr/titres/rmdm4m6L5fVaC02ZTUbtzW17
https://camino.beta.gouv.fr/titres/1gEXs3M0nUjwKxZh7siIgl52
https://camino.beta.gouv.fr/titres/DiYVd2IbBsytqBBGhlDWUIU5
https://camino.beta.gouv.fr/titres/JN5uz3RUAfM7l5lsG4EbjmlP
https://camino.beta.gouv.fr/titres/xuwWiEEU094RqAcCqZEToKPV
https://camino.beta.gouv.fr/titres/Ky5LJvuD9zjYluKXPvMyfH2e
https://camino.beta.gouv.fr/titres/oxMJ8Vp1TXWRN27uarBv8jYU

**Comment by pohayscamino** [comment]
Vous pouvez rendre visibles tous ces titres. j'ai eu la confirmation.
