### ISSUE TITLE
bug(depôt) : Permettre de supprimer des fichiers déposés

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#880]
Je dois pouvoir supprimer un fichier que j'ai déposé : https://camino.beta.gouv.fr/etapes/m-pr-lodeve-2023-oct01-mfr01/edition

![Image](https://github.com/MTES-MCT/camino/assets/144020267/e012b815-a250-4d5f-910e-479bcd61b26f)

**Comment by MichaelBitard** [comment]
Je pense que le but de déposer une demande c'est justement de ne plus pouvoir l'éditer.

C'est aussi pour ça qu'il y'a les étapes "Modifications de la demande", pour éviter que l'on puisse modifier a posteriori une demande déposée et ainsi changer les règles du jeu.

Après dans ce cas là si il s'agit d'une erreur de saisie, on peut aller supprimer "à la main" le fichier nous même en production, mais ça doit rester une opération exceptionnelle et, à mon humble avis, même les "super" ne doivent pas avoir le droit de modifier une demande déposée

**Comment by MichaelBitard** [comment]
> Par contre je pense que je me suis fait avoir car je n'ai pas cliqué sur le bouton déposer. Mais j'ouvre un autre ticket pour ça

T'arrives à reproduire ce bug là ? Parce que c'est grave :)

**Comment by pohayscamino** [comment]
j'essaie en preprod mais je pense que j'ai pas déposé mais j'ai créé une l'étape suivante pour déposer l'AR qui a du le déposer automatiquement. C'est possible ça?

**Comment by MichaelBitard** [comment]
Ça parait improbable.

T'as crée l'étape "Dépot de la demande" manuellement ?

**Comment by pohayscamino** [comment]
Je n'arrive pas à le refaire en preprod. Ca me met bien "Erreur : Error: la démarche n’est pas valide" quand j'essaie de faire l'étape d'après

**Comment by pohayscamino** [comment]
Non alors j'ai du déposer et j'ai vu l'erreur après. C'est de ma faute

**Comment by MichaelBitard** [comment]
Ok pas de souci, à voir si on arrive à le reproduire.

Le fichier a été supprimé de la production !
