### ISSUE TITLE
feat(import): permettre d’importer les périmètres multipolygone

### ISSUE THREAD

**Issue by vmaubert** [MTES-MCT/camino#881]
POH : « Sur le titre suivant : https://preprod.camino.beta.gouv.fr/titres/f-cx-glageon-couplevoie-1825?demarcheSlug=f-cx-glageon-couplevoie-1825-exp01

J'ai voulu déposer une extension de périmètre en déposant un multipolygone mais un seul des deux polygone a été uploadé »

**Comment by vmaubert** [comment]
@pohayscamino Oui on ne peut pas avec le fichier que tu m’as envoyé par email. 
Dans ce fichier ce n’est pas un « Multipolygone », mais une liste de 2 multipolygones.

On peut utiliser une fonction de QGIS qui permet de fusionner les 2 multipolygones, la forme finale sera respectée mais le tableau de points sera différents (donc différents de la demande).

**Comment by pohayscamino** [comment]
Non l'erreur était de mon côté. C'était deux polygones et pas un multipolygone comme prévu. C'est tout bon.
