### ISSUE TITLE
bug(frise) : Date de validité d'une mutation

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#883]
Une mutation ne peut pas être une phase. Il ne faut pas prendre en compte la date de fin de mutation dans la frise chronologique. Il faut même supprimer cette date
Exemple : https://preprod.camino.beta.gouv.fr/titres/m-cx-antully-1973?demarcheSlug=m-cx-antully-1973-mut01

L'extension de périmètre ne doit pas avoir de date de fin non plus.
Exemple : https://preprod.camino.beta.gouv.fr/titres/m-cx-esperance-2012?demarcheSlug=m-cx-esperance-2012-pro01

**Comment by pohayscamino** [comment]
Exemples 

![Image](https://github.com/MTES-MCT/camino/assets/144020267/1764f3ab-7c7b-4589-88fd-a1fb42bd247d)
![Image](https://github.com/MTES-MCT/camino/assets/144020267/7b88aa76-77f8-4612-8dc7-3e4b44caeae0)

**Comment by MichaelBitard** [comment]
Standby pour le moment, les modifications ont été faites directement en production.

Il faudrait qu'on limite certains champs dans l'édition des étapes

**Comment by pohayscamino** [comment]
On n'affiche pas les champs date de fin sur les mutations et les extensions de périmètres

**Comment by MichaelBitard** [comment]
Il y'a, en production, 8 démarches (et 10 étapes) qui ont ces valeurs de mises.


https://camino.beta.gouv.fr/demarches/pECTaTim3xFgKlFOEOxpIbaq
https://camino.beta.gouv.fr/demarches/QMhQmzg7dMAnie5kD8xgtSmS
https://camino.beta.gouv.fr/demarches/zqsp4B89FdzIXdcNCSPr7lXN
https://camino.beta.gouv.fr/demarches/7gUj2ytFvdOoFQZ8Kf3JFDSi
https://camino.beta.gouv.fr/demarches/zbfPf7WQvFH0NFE20scYfp2a
https://camino.beta.gouv.fr/demarches/zV9fpSYlXgytYkV4cbY42mgk
https://camino.beta.gouv.fr/demarches/aXVb1In92banC0uoJylwV5Aa
https://camino.beta.gouv.fr/demarches/5te9zDFOvWMNRAuvU0iqSUiI

On te laisse corriger ça @pohayscamino et on supprime l'édition de ces champs après.


La requête : 

```sql
select * from titres_etapes te 
join titres_demarches td ON td.id = te.titre_demarche_id 
where (date_debut is not null 
or date_fin is not null
or duree is not null)
and td.type_id in ('mut', 'exs');
```

**Comment by pohayscamino** [comment]
J'ai tout corrigé sauf le titre suivant pour lequel je n'arrive pas à déposer de périmètre. Il ne fait rien quand je dépose un fichier.

**Comment by MichaelBitard** [comment]
@pohayscamino tu parles de quel titre ?

**Comment by pohayscamino** [comment]
https://camino.beta.gouv.fr/demarches/zbfPf7WQvFH0NFE20scYfp2a

**Comment by MichaelBitard** [comment]
Ok si ça te va on supprime directement en base ?

**Comment by pohayscamino** [comment]
oui ça me va

**Comment by MichaelBitard** [comment]
C'est fait !
