### ISSUE TITLE
feat(instruction) : Mieux séparer le résumé des démarches

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#889]

**Comment by pohayscamino** [comment]
Je trouve que la séparation entre le résumé et la liste des étapes n'est pas assez claire. Peut être entourer la partie résumé avec un cadre gris ou autre chose



![Image](https://github.com/MTES-MCT/camino/assets/144020267/ee666f01-2de6-4f21-8319-a490fec81f49)

**Comment by SarahPelt** [comment]
pour les espacements : 
- div "dsfr" : padding : 40px;
- div autour de "phases" : padding-top: 24px; padding-bottom:40px;
- div autour d'octroi : padding-top : 40px;
- div autour des "étapes" : margin-top : 56px;

**Comment by pohayscamino** [comment]
Ok sauf pour le padding-bottom:40px;  de "phases" car ça éloigne trop le titre de la frise je trouve.



![Image](https://github.com/MTES-MCT/camino/assets/144020267/19c415d2-bec6-4ae4-8916-f777b3a8c792)

Vous pouvez essayer de mettre la même séparation que sous la frise mais une ligne plus courte? Un peu comme ça.



![Image](https://github.com/MTES-MCT/camino/assets/144020267/40fa7be3-514a-4f05-93a0-fd716862a7a0)
