### ISSUE TITLE
bug(instruction) : Superpositions pas indiquées

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#897]
Dans le titre suivant : https://preprod.camino.beta.gouv.fr/titres/m-pr-test-toto-per-2023?demarcheSlug=m-pr-test-toto-per-2023-oct01

J'ai déposé un périmètre qui est superposé avec le titre "Takari Sud Est". Je n'ai pas eu de message qui me l'indiquait.

**Comment by vmaubert** [comment]
Je ne sais pas avec quel utilisateur tu étais connecté, mais ces alertes sont affichées que pour les Super et les Administrations.
On ne les affiche pas pour les Entreprises, car on pourrait faire "fuiter' de l'information confidentielle.
