### ISSUE TITLE
bug(instaruction) : Statut de la demande incompréhensible

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#899]
J'ai voulu faire une demande pour le titre : https://preprod.camino.beta.gouv.fr/etapes/creation?demarche-id=m-pr-test-toto-per-0000-oct01

J'ai pleins de statuts que je peux sélectionner ce qui n'est pas compréhensible.

![Image](https://github.com/MTES-MCT/camino/assets/144020267/3713e29c-8ff3-47cb-b7e7-d44b68be721f)

Quand je sélectionne "en construction", ça fait disparaitre le champs "statut" et ça crée les deux boutons pour le dépôt

![Image](https://github.com/MTES-MCT/camino/assets/144020267/4e40b0ec-8515-4c35-bc8b-4f2e6ba53d20)

Quand je sélectionne "fait", ça laisse le champs "statut" et mais ça ne crée qu'un seul bouton "enregistrer"

![Image](https://github.com/MTES-MCT/camino/assets/144020267/a9445ec9-8d0b-457e-8987-bd7df35566cc)

**Comment by MichaelBitard** [comment]
Alors, le seul "bug" c'est les multiples statuts, ça fait longtemps que c'est là, mais comme c'est disponible que pour les comptes super, on ne l'a pas corrigé.

Pour le reste de ce que tu décris, c'est le comportement "normal" de la complexité de la double étape "Demande" et "Dépot de la demande"

En fait quand tu mets le statut à "En construction" (ce qu'un utilisateur normal ne peut pas faire, c'est son statut par défaut), on masque le statut et on ajoute un bouton pour pouvoir déposer le dossier (ce qui passe le statut de cette étape à "Fait" et crée automagiquement l'étape "Dépôt de la demande")

Quand (avec tes droits de "super") tu passes le status de l'étape à "fait", alors t'es en "mode manuel" et c'est à toi de créer ensuite l'étape de "Dépôt de la demande"


Je passe cette issue en "close", n'hésite pas à la réouvrir si tu n'es pas d'accord avec ce que j'ai expliqué :)
