### ISSUE TITLE
bug(instruction) : Prolongation pendant octroi

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#903]
Dans le titre suivant : J'avais le titre suivant : https://preprod.camino.beta.gouv.fr/titres/m-pr-test-toto-per-2023?demarcheSlug=m-pr-test-toto-per-2023-pr101

J'étais en train de créer mes étapes de la démarche d’octroi. Elle était donc en cours d'instruction. Une envie soudaine de créer une démarche de prolongation m'est venue. Ça a tout effacé et mis le titre en échu. 

Même si la situation a peu de chance d'arriver ça semble avoir des conséquences étranges

**Comment by MichaelBitard** [comment]
Nan mais @pohayscamino t'es super, on a des droits de fou dans tous les sens pour pouvoir faire n'importe quoi :)

Si tu fais n'importe quoi, ça fait n'importe quoi :)

Comme disait un philosophe : Un grand pouvoir implique de grandes factures d'électricité

Oui je sais ça ne veut rien dire, mais c'est la fin de journée

**Comment by pohayscamino** [comment]
Oui c'est vrai lol. Je vais faire mes recettes et tests en tant qu'admin central plutôt que super. Ce sera plus cohérent.
