### ISSUE TITLE
bug(carte) : Les points créés dans QGIS s'inverse dans CAMINO

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#909]
J'ai créé le périmètre suivant dans QGIS

![Image](https://github.com/MTES-MCT/camino/assets/144020267/fa1e1ee8-16d5-4e7f-aaa3-c50f409461e9)

L'enchainement des points est dans le sens horaire.

Je l'ai déposé sur Camino et ma liste de points est maintenant dans le sens anti-horaire.

![Image](https://github.com/MTES-MCT/camino/assets/144020267/30e5cd3a-0b26-4019-8f39-f86b368335aa)

Ils ont donc été inversés

**Comment by pohayscamino** [comment]
C'est toujours le cas. Le premier point créé lors de la création du polygone est le dernier sur Camino et l'ordre des points est toujours en sens horaire.

Ça veut dire qu'il va falloir mettre un bouton pour nommer les points.

**Comment by MichaelBitard** [comment]
Tout est inversé ou seulement le premier qui se retrouve à la fin ?
Tu as regardé dans le geojson généré par QGIS et ils sont dans le bon ordre ou ils sont inversés ?

**Comment by MichaelBitard** [comment]
@pohayscamino je viens de tester chez moi et ça n'inverse pas les points :sob:

**Comment by MichaelBitard** [comment]
Par contre, si dans QGIS, je change de référentiel ( je passe de WGS84 à du lambert 93 ) alors là les points ne sont plus dans le même ordre. C'est ça qui se produit chez toi ?

**Comment by pohayscamino** [comment]
J'ai refait des tests l'ordre finalement ça fonctionne bien. 
J'avais sauvegardé mon fichier (initialement en 4326) dans QGIS en changeant le SRID (à 2154). Là l'ordre devient automatiquement le sens horaire. 

[test_sens_anti_horaire_srid.zip](https://github.com/MTES-MCT/camino/files/14184288/test_sens_anti_horaire_srid.zip)

**Comment by pohayscamino** [comment]
Oui mais pour le coup j'ai aussi ouvert un périmètre qui était dans le sens anti horaire quand je l'ai créé et sur Camino et sur Qgis j'ai juste déplacé un point et ajouté un point. J'ai sauvegardé ma couche et quand je l'ai redéposé les points étaient revenus dans le sens horaire.

Ça montre bien que QGIS doit réenregistrer bizarrement des géométries qui fait que sans le bouton points, si tu veux un ordre particulier à tes points faut faire une géométrie nickelle dès le premier coup sinon tu es bon pour la recommencer de 0.

**Comment by pohayscamino** [comment]
Oui tu peux fermer le ticket car c'est bon du coup
