### ISSUE TITLE
feat(stats) : refonte des stats globales

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#914]
Ne plus utiliser Matomo pour nos productions statistiques et modifier l'onglet "général" de la page stats en fonction des spécifications : https://docs.google.com/presentation/d/1cTBlmO4UrLoF2ZYWwYB2MgaIXaGApx5U/edit?usp=drive_link&ouid=100327782879125411786&rtpof=true&sd=true

**Comment by vmaubert** [comment]
L'url https://camino.beta.gouv.fr a pour code de marquage 1667

Le code 1667 a été créé pour le site "Internet Camino (cadastre minier numérique)"

Personne ayant accès :
pierre-olivier.hays@developpement-durable.gouv.fr

Pour réaliser le marquage du site, vous trouverez des informations et un exemple sur cette page :
http://numerique.metier.e2.rie.gouv.fr/acces-a-matomo-pour-des-applications-ou-sites-non-a4846.html?id_rub=1548.

L’URL à utiliser est : audience-sites.din.developpement-durable.gouv.fr

Un compte vous a été créé pour la consultation des statistiques. Les informations concernant l’utilisation de l’outil sont disponibles ici : http://numerique.metier.e2.rie.gouv.fr/presentation-de-l-outil-matomo-a4542.html?id_rub=1548

**Comment by vmaubert** [comment]
@vmaubert Moyen d’avoir accès au matomo ? 
Car je viens de faire les modifs mais je ne peux rien vérifier :-/

**Comment by pohayscamino** [comment]
Je me connecte sur cet URL :  https://stats.data.gouv.fr/index.php?module=Login&idSite=109&period=range&date=previous30

**Comment by vmaubert** [comment]
C’est l’ancien celui-ci, le nouveau c’est dans le message un peu plus haut => https://audience-sites.din.developpement-durable.gouv.fr/index.php?module=CASLogin&action=login
