### ISSUE TITLE
feat(périmètre) : Les titulaires peuvent déposer des périmètres avec plus de 4 points pour les AEX et ARM

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#918]
Pour les AEX et ARM il ne faut plus limiter les périmètres à 4 points

**Comment by MichaelBitard** [comment]
C'est déjà le cas, cette restriction n'existe pas.

À moins qu'on ait raté un bug quelque part, mais en preprod, en tant que utilisateur entreprise, j'ai bien pu déposer un gros périmètre pour une ARM et pour une AEX
