### ISSUE TITLE
feat(carte) : ajouter le sexadecimale des coordonnées du 4326

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#919]
Il faut que le SRID en degré (4326) soit visible en décimale mais aussi en degré minute décimale comme sur le titre : https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000028253258

**Comment by MichaelBitard** [comment]
2 questions : 
1- On met quoi en entête de tableau ? (CF Screenshot)
2- Quand la personne appuie sur le bouton télécharger le csv, il se passe quoi ?

![2024-01-22_14-03-04_grim](https://github.com/MTES-MCT/camino/assets/414642/862ab854-6cbc-4713-b99f-a8cd90f3b203)
