### ISSUE TITLE
bug(instruction): uniformiser la prolongation1 et la prolongation2 de PER M et W

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#920]
Mettre les mêmes étapes pour les prolongations1 et 2 de PER W que celles des prolongations M

**Comment by MichaelBitard** [comment]
Lié à l'issue: 
  * #896 
Sur laquelle il manquait des trucs

**Comment by pohayscamino** [comment]
Dans le titre Sud Atlantique, impossible de déposer les avis des services : https://camino.beta.gouv.fr/titres/w-pr-sud-atlantique-2016?demarcheSlug=w-pr-sud-atlantique-2016-pr101

Dans le titre Platin de Grave qui a deja été uniformisé c'est ok : https://camino.beta.gouv.fr/titres/w-cx-platin-de-grave-2003?demarcheSlug=w-cx-platin-de-grave-2003-pro01

L'uniformisation prolongation M et W avait été faite dans ce ticket : https://github.com/orgs/MTES-MCT/projects/6/views/2?filterQuery=prolongation&pane=issue&itemId=49437484

**Comment by MichaelBitard** [comment]
Cette prise de tête de fou haha.

Attends, dans ce ticket là https://github.com/orgs/MTES-MCT/projects/6/views/2?filterQuery=prolongation&pane=issue&itemId=49437484 (qui est le ticket #893)

Tu parles de 

> Mettre les mêmes étapes pour les prolongations de PER W que celles des prolongations M

Et en commentaire tu mets ce titre --> https://camino.beta.gouv.fr/demarches/w-cx-platin-de-grave-2003-pro01 qui est une **concession**

Mais le code qui a changé parle de pr1 et pr2, pour les **PXM** et **PXW** (PEX M et PEX W). donc RIEN à voir avec la demande...

Maintenant, tu veux que les étapes de prolongations 1 et 2 (pas la 'prolongation') des PER W soient les mêmes que les étapes de prolongations 1 et 2 des PER M.

On est d'accord ?

**Comment by MichaelBitard** [comment]
Point bonus, la prolongation 1 des PER M n'a **pas** la saisine des services de possible... donc en uniformisant, je ne répond pas à ton problème...

Je rajoute la saisine des services pour les prolongation 1 on est d'accord ?

**Comment by pohayscamino** [comment]
Bon je pense que le mieux c'est d'attendre qu'on ait avancé sur nos travaux sur les démarches pour tout uniformiser. Là je ne maitrise pas assez ce qui est dans le code et les impacts.

Pour le moment dans ce cas juste ajouter la saisine des services et les étapes d'avis (le mêmes que celles pour la prolongation 1 d'une concession) dans les prolongations 1 de PER. Comme ça ma collègue ne sera plus bloquée.

**Comment by pohayscamino** [comment]
Je ne peux pas déposer d'avis dans ce titre : https://camino.beta.gouv.fr/titres/w-pr-sud-atlantique-2016?demarcheSlug=w-pr-sud-atlantique-2016-pr101
