### ISSUE TITLE
feat(geothermie) : Permettre de déposer d'anciens PEX geothermie

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#926]
Pour que les services remplissent les anciens PEX géothermie il faut leur permettre de créer l'étape "enquête publique" et de "Publication de décision au JORF" dès la création de la démarche. 

On peut dire que la machine ne dois être respectée que pour les titres déposés après le 01/01/2024

**Comment by MichaelBitard** [comment]
Ça me parait être une décision violente d'enlever la machine de tous les PEX Géothermie, sachant qu'ils sont tous compatibles avec la machine, sauf ces 3 démarches --> fqDEYKmkLijEx0b7HRmkXxUP fML5J37ugo6iWC3ugXfQ2AIk Umr7TPPxiuGDOzzlKfu4S8Dm

C'est quoi la problématique exacte ? Plutôt que nous proposer une solution, donne nous le problème.

Si, pour des raisons d'archivage, les services ne remplissent que 2 étapes (enquête publique, puis publication au JORF), on est capable d'adapter la machine pour qu'elle accepte que ces 2 étapes là soient possibles et passent le statut de la démarche à valide, et tout le tralala, il faut juste le spécifier.

**Comment by pohayscamino** [comment]
Yes  dans la plupart des cas ils ne sont capables que de remplir que les étapes d' "enquête publique" et de "Publication de décision au JORF", voir juste de "Publication de décision au JORF"

**Comment by vmaubert** [comment]
@pohayscamino Avec @MichaelBitard on propose la solution suivante : 
 - soit on respecte parfaitement la machine actuelle
 - soit on utilise une machine simplifiée qui permet d’ajouter seulement « enquête publique » et « publication au jorf ». Par contre nous avons regardé en prod, il y a 3 exceptions à la machine actuelle, et elles utilisent toutes l’étape « décision de l’administration ».  Est-ce qu’on devrait pas l’ajouter aussi ? Est-ce qu’il y a un ordre particulier à ces étapes ? Est-ce qu’elles sont toutes obligatoires ?

**Comment by pohayscamino** [comment]
Il faudrait qu'ils puissent choisir entre cette procédure simplifiée et la procédure complète (machine actuelle). A partir du 1er juillet 2024 par contre on imposera que le nouveau logigramme (post-réforme)

**Comment by MichaelBitard** [comment]
Oui c'est ce qu'on avait en tête

**Comment by pohayscamino** [comment]
Bon je viens d'échanger avec la DREAL, vu que la DGEC ne veut pas imposer Camino et que pour les PEX ce sont des demandes de titre et de travaux en parallèle, ça fait qu'ils déposent deja sur l'outil Gun. Donc il y a peu de chance qu'ils fassent le logigramme complet. Mais en échangeant avec certains de ses collègues ils ont l'air ok pour faire la procédure simplifiée.

Et ça va être pareil après la réforme donc faudra continuer de permettre les deux procédures.

**Comment by MichaelBitard** [comment]
Ces 3 démarches là, qui ne respectaient pas l'ancienne machine, ne respectent pas non plus la démarche simplifiée.

https://preprod.camino.beta.gouv.fr/demarches/fqDEYKmkLijEx0b7HRmkXxUP
https://preprod.camino.beta.gouv.fr/demarches/fML5J37ugo6iWC3ugXfQ2AIk
https://preprod.camino.beta.gouv.fr/demarches/Umr7TPPxiuGDOzzlKfu4S8Dm

**Comment by pohayscamino** [comment]
Vu les cas problématiques je change d'avis et demande que l'étape de "Publication au recueil des actes administratifs" soit optionnelle et pas obligatoire.

**Comment by MichaelBitard** [comment]
J'aurai du préciser pourquoi elles étaient pas bonnes:

https://preprod.camino.beta.gouv.fr/demarches/fqDEYKmkLijEx0b7HRmkXxUP => il y'a un dépôt de la demande et non une demande

https://preprod.camino.beta.gouv.fr/demarches/fML5J37ugo6iWC3ugXfQ2AIk => C'est une publication au JORF et non une Publication au recueil des actes administratifs

https://preprod.camino.beta.gouv.fr/demarches/Umr7TPPxiuGDOzzlKfu4S8Dm  => il y'a un dépôt de la demande suivi d'une modification de la demande.


La démarche simplifiée que tu as demandé et que nous avons implémenté et la suivante:


 *   "Demande"(optionnelle) et « enquête publique » (optionnelle) et « décision de l’administration » (obligatoire)
 *  "Publication au recueil des actes administratifs" (obligatoire)

Donc cest 3 demandes ne rentrent pas dans le cadre de la démarche simplifiée, et elles ne sont pas non plus valides en démarche "complètes"

Pour corriger les problèmes, je propose:

* Pour la première demande, on supprime le dépôt de la demande
* Pour la seconde, on supprime la "publication au JORF" et on crée la  Publication au recueil des actes administratifs à la place
* Pour la dernière, on supprime le dépôt de la demande et la modification de la demande

T'en penses quoi ?

**Comment by pohayscamino** [comment]
Je suis d'accord pour le premier et le troisième (je vais faire la modif manuellement et créer des étapes de dépôt pour garder la date). Pour le second je dois avoir un retour de madame Kanta. Peut être que va falloir ajouter "Publication au JORF" (optionnelle) mais je ne comprends pas la règle quand c'est au JORF et quand ça ne l'est pas.
