### ISSUE TITLE
bug(participation public) : Documents non telechargeables si admin

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#931]
Pour les consultations en cours : https://www.economie.gouv.fr/consultation-demande-octroi-permis-exclusif-recherches-la-plaine-du-rhin

On a essayé d'ouvrir un documents connecté sur mon profil super admin (mais ils ont le même problème avec les profils administration) : https://camino.beta.gouv.fr/apiUrl/download/fichiers/2024-01-15-dos-b0c35466

Il y a marqué "Unauthorized"

Quand je me déconnecte par contre ça fonctionne. c'est plus la même URL : https://camino.beta.gouv.fr/apiUrl/download/fichiers/2024-01-15-dos-1a436f40

**Comment by vmaubert** [comment]
@pohayscamino corrigé directement en prod. Pour que tu puisses voir la correction il faut se déconnecter puis se reconnecter

**Comment by pohayscamino** [comment]
ok c'est bon
