### ISSUE TITLE
bug(carte) : Les coordonnées 4326 sont à modifier

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#940]
Les longitudes et latitudes en 4326 doivent être arrondies à 4 chiffres décimales
Les autres longitudes et latitudes en 4326 doivent être en X°X,XXXX'

**Comment by MichaelBitard** [comment]
Pour la partie arrondies, ça sera fait avec l'issue #755

**Comment by pohayscamino** [comment]
On prend la longitude Ouest dans les décisions car le méridien traverse la France et les demandes sont essentiellement à l'ouest (Océan Atlantique et DROM).
