### ISSUE TITLE
bug(carte) : Scroll sur la page compliqué quand il y a des cartes

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#942]
Des agents m'indiquent que ils ont du mal à scroller sur les pages à cause des cartes. Dès que le sourie arrive sur une carte ça scroll dans la carte plutot que sur la page. 

Pourrait-on revenir à ctrl+scroll pour scroller dans les cartes sur la page détaillée d'un titre?

De plus on va surement supprimer les marges donc là ça deviendra vraiment compliqué de scroller

**Comment by MichaelBitard** [comment]
Haha c'est énorme, parce que tu voulais l'inverse sur la page principale :)

**Comment by pohayscamino** [comment]
yes et je continue à penser que sur la page principale il vaudrait mieux pas de ctrl parceque la page est constituée que d'une carte donc y a pas vraiment de raison de scroller sur la page. 
Mais dans nos pages détaillées des titres il y a pleins d'info sur la page et donc y a besoin de scroller. Les utilisateurs vont beaucoup moins utiliser les petites cartes pour dezzomer ou se déplacer.

Par contre je ne sais pas si c'est top d'avoir pas la même chose sur la carte principale et les petites cartes (faudra que je demande à Sarah). Tant qu'à choisir je préfère du ctrl+scroll partout.
