### ISSUE TITLE
feat(stats datagouv) : publier sur datagouv le schéma de données pour 3 stats

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#954]

**Comment by pohayscamino** [comment]
remplir un [tableau](https://docs.google.com/spreadsheets/d/1zRJFz5_zjmuslRpF7yzQUTfDWE2z1-jYSK9xAf8vMgE/edit?usp=sharing) à la main avec les [indicateurs "stables"](https://camino.beta.gouv.fr/statistiques/globales) de Camino : colonnes et description du schéma à retrouver[ ici](https://schema.data.gouv.fr/etalab/schema-impact-service-public-numerique/0.3.0/documentation.html#propriete-est-cible). Si utile : [exemple des stats data gouv](https://www.data.gouv.fr/fr/datasets/indicateurs-dimpact-de-data-gouv-fr/#/resources)

Contact chez data gouv pour les questions : @Pierlou Ramade sur mattermost

    présentation aux devs pour évaluer la charge de travail et fixer les prochaines étapes opérationnelles 

Documents utiles à leur communiquer : 

    Présentation du schéma : https://schema.data.gouv.fr/etalab/schema- impact-service-public-numerique/0.3.0/
    exemple d'utilisation du schéma : https://www.data.gouv.fr/fr/datasets/indicateurs-dimpact-de-data-gouv-fr/#/resources
    le code complet utilisé par data gouv pour l'automatisation : [datagouvfr_data_pipelines/dgv/impact at main · etalab/datagouvfr_data_pipelines (github.com)](https://github.com/etalab/datagouvfr_data_pipelines/tree/main/dgv/impact)

**Comment by pohayscamino** [comment]
publier sur https://demo.data.gouv.fr/fr/

Contact : @Pierlou Ramade sur mattermost

**Comment by pohayscamino** [comment]
Planning : début février 1-3 stats

février : stats de base

mars-avril car après 2 ateliers impacts : page stat complète :

**Comment by MichaelBitard** [comment]
On a publié à la main le fichier généré par notre API en local.

On a décidé de le publier au format JSON, ça a l'air de fonctionner --> https://www.data.gouv.fr/fr/datasets/cadastre-minier/

Dès que cette PR part en prod, on pourra modifier la page de data.gouv.fr pour pointer sur la nouvelle URL de statistique de camino, plutôt que d'utiliser le fichier qu'on a uploadé

**Comment by Pierlou** [comment]
Bonjour, le schéma est au format TableSchema et attend forcément un csv.

**Comment by MichaelBitard** [comment]
Ok c'est noté, on fait le changement
