### ISSUE TITLE
bug(instruction) : Liste déroulante passe sous bouton

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#980]
Dans le formulaire d'une étape, la liste déroulante passe sous le bouton déposer ce qui rend un truc bizzare

![Image](https://github.com/MTES-MCT/camino/assets/144020267/aad3ff9e-0c4c-4bdb-8f0a-7623ff514bf8)

**Comment by MichaelBitard** [comment]
Ça a été fixé lors de la mise en preprod. Je te laisse réouvrir si ce n'est pas bon

**Comment by pohayscamino** [comment]
super c'est corrigé
