### ISSUE TITLE
feat(instruction) : faire hériter les démarches

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#981]
Même principe que les hérédités entre étapes, mais les faire entre démarches

**Comment by MichaelBitard** [comment]
Alors ça, c'est un gros chantier qu'il va falloir détailler et mieux spécifier si on veut avoir une chance de ne pas terminer avec une usine à gaz.
On va avoir besoin de tout là, à la fois de la réflexion en amont (que veulent les utilisateurs), de l'UX, et aussi quelles contraintes sont présentes dans camino

**Comment by pohayscamino** [comment]
Ce n'est pas un héritage mais une copie des données de l'étape de décision de l'administration de la dernière démarche au moment de la création de la demande
