### ISSUE TITLE
feat(tableau) : Longitude/latitude trop précis

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#983]
Pour moi les coordonnées 4326 ont trop de décimales. 4 décimales c'est bien. Je ne pense pas que les agents aient rempli avec autant.

**Comment by MichaelBitard** [comment]
Malheureusement si, on a des trucs hyper précis qui nous viennent de ce que les utilisateurs ont saisi.

On fait quoi du coup ? On arrondit ? C'est dangereux non ? Si les utilisateurs veulent nous envoyer des trucs ultra précis (ou si le JORF a une énorme précision ?)

**Comment by MichaelBitard** [comment]
On a pris un point au hasard, visuellement la différence ça donne ça :

![2024-02-13_14-52-58_grim](https://github.com/MTES-MCT/camino/assets/414642/a6a878cd-4bb8-4363-9d41-f1e155dab564)


![2024-02-13_14-53-04_grim](https://github.com/MTES-MCT/camino/assets/414642/1d2ee261-46f3-4c89-87e8-3128741cfd06)

Je trouve ça violent comme différence personnellement, maintenant, si tu nous dis que ce n'est pas grave, alors on fait une migration pour tout passer à 4 décimales.
Mais je suis prêt à parier qu'on va avoir des retours comme quoi les points sont plus au bon endroit.

De plus, c'est une migration définitive, on perd la donnée, le retour en arrière est quasi impossible (plus le temps passera plus ça sera compliqué)

**Comment by pohayscamino** [comment]
Ah oui ok c'est un peu violent effectivement. Tt tu pourrais me faire le tests à 5 décimales?

D'après mes calculs on devrait avoir les valeurs suivantes mais je veux bien confirmation : 
Si on arrondi à 10^-4 on crée une différence d'environ 7m
Si on arrondi à 10^-5 on crée une différence d'environ 1m
Si on arrondi à 10^-6 on crée une différence d'environ 0.5m

Si c'est bien le cas, la DGTM est ok pour arrondir à 5 décimales. je demande à la DGALN et la DGEC

**Comment by pohayscamino** [comment]
Bon commentaire de la DGEC : 
0,5 me parait acceptable mais il faudrait vérifier si ça ne crée pas trop de superstitions entre les titres
En cas de litiges ou de questionnement on pourrait expliquer que pour des raisons techniques d’éventuelles superpositions peuvent arriver mais qu’elles n’existent pas en réalité


On ne pourrait pas juste ne pas afficher toutes les décimales mais que en base et sur la carte ça les garde toutes? Un peu comme on a fait dans les matrices fiscales

**Comment by pohayscamino** [comment]
Bon ils sont compliqués et changent d'avis tout le temps. J'ai fait un point avec EARM2 sur ce sujet et je reviens sur ce que j'ai dit et il faut qu'on en discute.

Est-ce que j'ai bien compris comment ça fonctionne actuellement?
- L'agent rentre un périmètre en 2154
- Les coordonnées sont transformées en 4326 ultra précis sans perte d'info
- Quand on regarde le tableau en 215, les coordonnées sont transformées en 2154 sans perte d'info, puis sont arrondies à trois chiffres après la virgule
