### ISSUE TITLE
feat(instruction) : Je ne dois pas avoir à déposer des rapports d'activité postérieurs au retrait d'une décision.

### ISSUE THREAD

**Issue by pohayscamino** [MTES-MCT/camino#987]
Dans ce titre j'ai retiré la décision en 2023 mais les rapports absents de l'année 2023 sont toujours demandés : https://preprod.camino.beta.gouv.fr/titres/m-ax-crique-sainte-helene-1-2022?demarcheSlug=m-ax-crique-sainte-helene-1-2022-ret01

**Comment by MichaelBitard** [comment]
Oui et maintenant tu peux les supprimer j'imagine non ? On ne supprime pas les rapports d'activités, trop dangereux

**Comment by MichaelBitard** [comment]
Et par défaut tu ne peux supprimer les rapports d'activités, que si tu es super **et** qu'ils sont supprimables
